--!native
--!optimize 2
--!nocheck
--!nolint
--#selene: allow(unused_variable, global_usage)
-- Client generated by Zap v0.6.28 (https://github.com/red-blox/zap)
local RunService = game:GetService("RunService")
local ReplicatedStorage = game:GetService("ReplicatedStorage")
if RunService:IsServer() then
	error("Cannot use the client module on the server!")
end

if not _G.__ZAP then
	_G.__ZAP = { ["FootyenZap"] = {} }
elseif not _G.__ZAP["FootyenZap"] then
	_G.__ZAP["FootyenZap"] = {}
elseif _G.__ZAP["FootyenZap"]["FOOTYEN"] ~= nil then
	error(`There is already an instance of Zap with the same remote_scope of FOOTYEN, remote_folder of FootyenZap and the version of {_G.__ZAP["FootyenZap"]["FOOTYEN"]}. Change the remote_scope or remote_folder option of both Zap instances`)
end

_G.__ZAP["FootyenZap"]["FOOTYEN"] = "0.6.28"

local outgoing_buff: buffer
local outgoing_used: number
local outgoing_size: number
local outgoing_inst: { Instance }
local outgoing_apos: number
local outgoing_ids: { number }

local incoming_buff: buffer
local incoming_read: number
local incoming_inst: { Instance }
local incoming_ipos: number
local incoming_ids: { number }

-- thanks to https://dom.rojo.space/binary.html#cframe
local CFrameSpecialCases = {
	CFrame.Angles(0, 0, 0),
	CFrame.Angles(math.rad(90), 0, 0),
	CFrame.Angles(0, math.rad(180), math.rad(180)),
	CFrame.Angles(math.rad(-90), 0, 0),
	CFrame.Angles(0, math.rad(180), math.rad(90)),
	CFrame.Angles(0, math.rad(90), math.rad(90)),
	CFrame.Angles(0, 0, math.rad(90)),
	CFrame.Angles(0, math.rad(-90), math.rad(90)),
	CFrame.Angles(math.rad(-90), math.rad(-90), 0),
	CFrame.Angles(0, math.rad(-90), 0),
	CFrame.Angles(math.rad(90), math.rad(-90), 0),
	CFrame.Angles(0, math.rad(90), math.rad(180)),
	CFrame.Angles(0, math.rad(-90), math.rad(180)),
	CFrame.Angles(0, math.rad(180), math.rad(0)),
	CFrame.Angles(math.rad(-90), math.rad(-180), math.rad(0)),
	CFrame.Angles(0, math.rad(0), math.rad(180)),
	CFrame.Angles(math.rad(90), math.rad(180), math.rad(0)),
	CFrame.Angles(0, math.rad(0), math.rad(-90)),
	CFrame.Angles(0, math.rad(-90), math.rad(-90)),
	CFrame.Angles(0, math.rad(-180), math.rad(-90)),
	CFrame.Angles(0, math.rad(90), math.rad(-90)),
	CFrame.Angles(math.rad(90), math.rad(90), 0),
	CFrame.Angles(0, math.rad(90), 0),
	CFrame.Angles(math.rad(-90), math.rad(90), 0),
}

local function alloc(len: number)
	if outgoing_used + len > outgoing_size then
		while outgoing_used + len > outgoing_size do
			outgoing_size = outgoing_size * 2
		end

		local new_buff = buffer.create(outgoing_size)
		buffer.copy(new_buff, 0, outgoing_buff, 0, outgoing_used)

		outgoing_buff = new_buff
	end

	outgoing_apos = outgoing_used
	outgoing_used = outgoing_used + len

	return outgoing_apos
end

local function read(len: number)
	local pos = incoming_read
	incoming_read = incoming_read + len

	return pos
end

local function save()
	return {
		buff = outgoing_buff,
		used = outgoing_used,
		size = outgoing_size,
		inst = outgoing_inst,
		outgoing_ids = outgoing_ids,
		incoming_ids = incoming_ids,
	}
end

local function load(data: {
	buff: buffer,
	used: number,
	size: number,
	inst: { Instance },
	outgoing_ids: { number },
	incoming_ids: { number },
})
	outgoing_buff = data.buff
	outgoing_used = data.used
	outgoing_size = data.size
	outgoing_inst = data.inst
	outgoing_ids = data.outgoing_ids
	incoming_ids = data.incoming_ids
end

local function load_empty()
	outgoing_buff = buffer.create(64)
	outgoing_used = 0
	outgoing_size = 64
	outgoing_inst = {}
	outgoing_ids = {}
	incoming_ids = {}
end

load_empty()

local types = {}

local polling_queues_reliable = {}
local polling_queues_unreliable = {}
if not RunService:IsRunning() then
	local noop = function() end
	return table.freeze({
		SendEvents = noop,
		UpgradePet = table.freeze({
			Call = noop
		}),
		SummonPets = table.freeze({
			Call = noop
		}),
		SetPetEquipped = table.freeze({
			Call = noop
		}),
		RequestSprint = table.freeze({
			Fire = noop
		}),
		PurchaseUpgrade = table.freeze({
			Call = noop
		}),
		PurchaseBootUpgrade = table.freeze({
			Call = noop
		}),
		PlayerStateSnapshot = table.freeze({
			SetCallback = noop
		}),
		PetInventorySnapshot = table.freeze({
			SetCallback = noop
		}),
		GetPlayerState = table.freeze({
			Call = noop
		}),
		GetPetInventory = table.freeze({
			Call = noop
		}),
		EquipBestPets = table.freeze({
			Call = noop
		}),
		DeletePets = table.freeze({
			Call = noop
		}),
		DeletePet = table.freeze({
			Call = noop
		}),
	}) :: Events
end
local remotes = ReplicatedStorage:WaitForChild("FootyenZap")

local reliable = remotes:WaitForChild("FOOTYEN_RELIABLE")
assert(reliable:IsA("RemoteEvent"), "Expected FOOTYEN_RELIABLE to be a RemoteEvent")


local function SendEvents()
	if outgoing_used ~= 0 then
		local buff = buffer.create(outgoing_used)
		buffer.copy(buff, 0, outgoing_buff, 0, outgoing_used)

		reliable:FireServer(buff, outgoing_inst)

		outgoing_buff = buffer.create(64)
		outgoing_used = 0
		outgoing_size = 64
		table.clear(outgoing_inst)
	end
end

RunService.Heartbeat:Connect(SendEvents)

local reliable_events = table.create(12)
local reliable_event_queue: { [number]: { any } } = table.create(12)
local function_call_id = 0
reliable_event_queue[0] = {}
reliable_event_queue[1] = {}
reliable_event_queue[10] = table.create(255)
reliable_event_queue[4] = table.create(255)
reliable_event_queue[7] = table.create(255)
reliable_event_queue[5] = table.create(255)
reliable_event_queue[6] = table.create(255)
reliable_event_queue[2] = table.create(255)
reliable_event_queue[3] = table.create(255)
reliable_event_queue[11] = table.create(255)
reliable_event_queue[9] = table.create(255)
reliable_event_queue[8] = table.create(255)
reliable.OnClientEvent:Connect(function(buff, inst)
	incoming_buff = buff
	incoming_inst = inst
	incoming_read = 0
	incoming_ipos = 0
	local len = buffer.len(buff)
	while incoming_read < len do
		local id = buffer.readu8(buff, read(1))
		if id == 0 then -- PlayerStateSnapshot
			local value
			local bool_1 = buffer.readu8(incoming_buff, read(1))
			value = {  }
			value["footyens"] = buffer.readu32(incoming_buff, read(4))
			value["footgems"] = buffer.readu32(incoming_buff, read(4))
			value["totalDistance"] = buffer.readf64(incoming_buff, read(8))
			value["bootsCollected"] = buffer.readu32(incoming_buff, read(4))
			value["activeBoots"] = buffer.readu8(incoming_buff, read(1))
			value["movementSpeedLevel"] = buffer.readu8(incoming_buff, read(1))
			value["studsPerCurrencyLevel"] = buffer.readu8(incoming_buff, read(1))
			value["currencyMultiplierLevel"] = buffer.readu8(incoming_buff, read(1))
			value["bootValueLevel"] = buffer.readu8(incoming_buff, read(1))
			value["spawnRateLevel"] = buffer.readu8(incoming_buff, read(1))
			value["maxActiveBootsLevel"] = buffer.readu8(incoming_buff, read(1))
			value["pickupRadiusLevel"] = buffer.readu8(incoming_buff, read(1))
			value["bootLifetimeLevel"] = buffer.readu8(incoming_buff, read(1))
			value["goldenChanceLevel"] = buffer.readu8(incoming_buff, read(1))
			value["goldenMultiplierLevel"] = buffer.readu8(incoming_buff, read(1))
			value["movementSpeed"] = buffer.readf64(incoming_buff, read(8))
			value["studsPerCurrency"] = buffer.readf64(incoming_buff, read(8))
			value["currencyMultiplier"] = buffer.readf64(incoming_buff, read(8))
			value["bootValue"] = buffer.readf64(incoming_buff, read(8))
			value["bootSpawnInterval"] = buffer.readf64(incoming_buff, read(8))
			value["bootMaxActive"] = buffer.readu8(incoming_buff, read(1))
			value["bootPickupRadius"] = buffer.readf64(incoming_buff, read(8))
			value["bootLifetime"] = buffer.readf64(incoming_buff, read(8))
			value["bootGoldenChance"] = buffer.readf64(incoming_buff, read(8))
			value["bootGoldenMultiplier"] = buffer.readf64(incoming_buff, read(8))
			value["petInventoryLimit"] = buffer.readu8(incoming_buff, read(1))
			value["petEmptySlots"] = buffer.readu8(incoming_buff, read(1))
			value["petInventoryCount"] = buffer.readu8(incoming_buff, read(1))
			value["petEquipLimit"] = buffer.readu8(incoming_buff, read(1))
			value["equippedPetCount"] = buffer.readu8(incoming_buff, read(1))
			value["petFootyenMultiplier"] = buffer.readf64(incoming_buff, read(8))
			value["petPassivePerSecond"] = buffer.readf64(incoming_buff, read(8))
			value["shopHasFootyenGain10x"] = bit32.btest(bool_1, 0b0000000000000001)
			value["shopHasMovementSpeed5x"] = bit32.btest(bool_1, 0b0000000000000010)
			value["shopHasTripleSummon"] = bit32.btest(bool_1, 0b0000000000000100)
			value["shopHasExtraEquipTwo"] = bit32.btest(bool_1, 0b0000000000001000)
			value["shopHasLuckySummon"] = bit32.btest(bool_1, 0b0000000000010000)
			value["shopHasBootMagnet"] = bit32.btest(bool_1, 0b0000000000100000)
			value["shopHasPetPassiveAura"] = bit32.btest(bool_1, 0b0000000001000000)
			value["shopExtraPetSlotsCount"] = buffer.readu16(incoming_buff, read(2))
			value["shopPetPassiveOverclockCount"] = buffer.readu8(incoming_buff, read(1))
			value["shopBootValueCoreCount"] = buffer.readu8(incoming_buff, read(1))
			value["isSprinting"] = bit32.btest(bool_1, 0b0000000010000000)
			value["sprintEndsAt"] = buffer.readf64(incoming_buff, read(8))
			value["cooldownEndsAt"] = buffer.readf64(incoming_buff, read(8))
			if reliable_events[0] then
				task.spawn(reliable_events[0], value)
			else
				table.insert(reliable_event_queue[0], value)
				if #reliable_event_queue[0] > 64 then
					warn(`[ZAP] {#reliable_event_queue[0]} events in queue for PlayerStateSnapshot. Did you forget to attach a listener?`)
				end
			end
		elseif id == 1 then -- PetInventorySnapshot
			local value
			value = {  }
			value["petInventoryLimit"] = buffer.readu8(incoming_buff, read(1))
			value["petEmptySlots"] = buffer.readu8(incoming_buff, read(1))
			value["petInventoryCount"] = buffer.readu8(incoming_buff, read(1))
			value["petEquipLimit"] = buffer.readu8(incoming_buff, read(1))
			value["equippedPetCount"] = buffer.readu8(incoming_buff, read(1))
			local len_1 = buffer.readu8(incoming_buff, read(1))
			assert(len_1 <= 45, "value is more than 45!")
			value["pets"] = table.create(len_1)
			for i_1 = 1, len_1 do
				local bool_2 = buffer.readu8(incoming_buff, read(1))
				local val_1
				val_1 = {  }
				local len_2 = buffer.readu8(incoming_buff, read(1))
				assert(len_2 <= 192, "value is more than 192!")
				val_1["uid"] = buffer.readstring(incoming_buff, read(len_2), len_2)
				assert(utf8.len(val_1["uid"]) ~= nil, "value is not valid utf-8")
				local len_3 = buffer.readu8(incoming_buff, read(1))
				assert(len_3 <= 128, "value is more than 128!")
				val_1["petId"] = buffer.readstring(incoming_buff, read(len_3), len_3)
				assert(utf8.len(val_1["petId"]) ~= nil, "value is not valid utf-8")
				val_1["level"] = buffer.readu8(incoming_buff, read(1))
				assert(val_1["level"] >= 1, "value is less than 1!")
				assert(val_1["level"] <= 5, "value is more than 5!")
				val_1["isEquipped"] = bit32.btest(bool_2, 0b0000000000000001)
				value["pets"][i_1] = val_1
			end
			if reliable_events[1] then
				task.spawn(reliable_events[1], value)
			else
				table.insert(reliable_event_queue[1], value)
				if #reliable_event_queue[1] > 64 then
					warn(`[ZAP] {#reliable_event_queue[1]} events in queue for PetInventorySnapshot. Did you forget to attach a listener?`)
				end
			end
		elseif id == 10 then -- UpgradePet
			local call_id = buffer.readu8(incoming_buff, read(1))
			local value
			local bool_3 = buffer.readu8(incoming_buff, read(1))
			value = {  }
			value["success"] = bit32.btest(bool_3, 0b0000000000000001)
			local len_4 = buffer.readu16(incoming_buff, read(2))
			assert(len_4 <= 640, "value is more than 640!")
			value["message"] = buffer.readstring(incoming_buff, read(len_4), len_4)
			assert(utf8.len(value["message"]) ~= nil, "value is not valid utf-8")
			local thread = reliable_event_queue[10][call_id]
			-- When using actors it's possible for multiple Zap clients to exist, but only one called the Zap remote function.
			if thread then
				task.spawn(thread, value)
			end
			reliable_event_queue[10][call_id] = nil
		elseif id == 4 then -- SummonPets
			local call_id = buffer.readu8(incoming_buff, read(1))
			local value
			local bool_4 = buffer.readu8(incoming_buff, read(1))
			value = {  }
			value["success"] = bit32.btest(bool_4, 0b0000000000000001)
			local len_5 = buffer.readu16(incoming_buff, read(2))
			assert(len_5 <= 640, "value is more than 640!")
			value["message"] = buffer.readstring(incoming_buff, read(len_5), len_5)
			assert(utf8.len(value["message"]) ~= nil, "value is not valid utf-8")
			value["spentFootgems"] = buffer.readu32(incoming_buff, read(4))
			value["remainingFootgems"] = buffer.readu32(incoming_buff, read(4))
			local len_6 = buffer.readu8(incoming_buff, read(1))
			assert(len_6 <= 3, "value is more than 3!")
			value["results"] = table.create(len_6)
			for i_2 = 1, len_6 do
				local bool_5 = buffer.readu8(incoming_buff, read(1))
				local val_2
				val_2 = {  }
				local len_7 = buffer.readu8(incoming_buff, read(1))
				assert(len_7 <= 192, "value is more than 192!")
				val_2["uid"] = buffer.readstring(incoming_buff, read(len_7), len_7)
				assert(utf8.len(val_2["uid"]) ~= nil, "value is not valid utf-8")
				local len_8 = buffer.readu8(incoming_buff, read(1))
				assert(len_8 <= 128, "value is more than 128!")
				val_2["petId"] = buffer.readstring(incoming_buff, read(len_8), len_8)
				assert(utf8.len(val_2["petId"]) ~= nil, "value is not valid utf-8")
				local len_9 = buffer.readu8(incoming_buff, read(1))
				assert(len_9 <= 64, "value is more than 64!")
				val_2["rarity"] = buffer.readstring(incoming_buff, read(len_9), len_9)
				assert(utf8.len(val_2["rarity"]) ~= nil, "value is not valid utf-8")
				val_2["level"] = buffer.readu8(incoming_buff, read(1))
				assert(val_2["level"] >= 1, "value is less than 1!")
				assert(val_2["level"] <= 5, "value is more than 5!")
				val_2["autoDeleted"] = bit32.btest(bool_5, 0b0000000000000001)
				value["results"][i_2] = val_2
			end
			local thread = reliable_event_queue[4][call_id]
			-- When using actors it's possible for multiple Zap clients to exist, but only one called the Zap remote function.
			if thread then
				task.spawn(thread, value)
			end
			reliable_event_queue[4][call_id] = nil
		elseif id == 7 then -- SetPetEquipped
			local call_id = buffer.readu8(incoming_buff, read(1))
			local value
			local bool_6 = buffer.readu8(incoming_buff, read(1))
			value = {  }
			value["success"] = bit32.btest(bool_6, 0b0000000000000001)
			local len_10 = buffer.readu16(incoming_buff, read(2))
			assert(len_10 <= 640, "value is more than 640!")
			value["message"] = buffer.readstring(incoming_buff, read(len_10), len_10)
			assert(utf8.len(value["message"]) ~= nil, "value is not valid utf-8")
			local thread = reliable_event_queue[7][call_id]
			-- When using actors it's possible for multiple Zap clients to exist, but only one called the Zap remote function.
			if thread then
				task.spawn(thread, value)
			end
			reliable_event_queue[7][call_id] = nil
		elseif id == 5 then -- PurchaseUpgrade
			local call_id = buffer.readu8(incoming_buff, read(1))
			local value
			local bool_7 = buffer.readu8(incoming_buff, read(1))
			value = {  }
			value["success"] = bit32.btest(bool_7, 0b0000000000000001)
			local len_11 = buffer.readu16(incoming_buff, read(2))
			assert(len_11 <= 640, "value is more than 640!")
			value["message"] = buffer.readstring(incoming_buff, read(len_11), len_11)
			assert(utf8.len(value["message"]) ~= nil, "value is not valid utf-8")
			local thread = reliable_event_queue[5][call_id]
			-- When using actors it's possible for multiple Zap clients to exist, but only one called the Zap remote function.
			if thread then
				task.spawn(thread, value)
			end
			reliable_event_queue[5][call_id] = nil
		elseif id == 6 then -- PurchaseBootUpgrade
			local call_id = buffer.readu8(incoming_buff, read(1))
			local value
			local bool_8 = buffer.readu8(incoming_buff, read(1))
			value = {  }
			value["success"] = bit32.btest(bool_8, 0b0000000000000001)
			local len_12 = buffer.readu16(incoming_buff, read(2))
			assert(len_12 <= 640, "value is more than 640!")
			value["message"] = buffer.readstring(incoming_buff, read(len_12), len_12)
			assert(utf8.len(value["message"]) ~= nil, "value is not valid utf-8")
			local thread = reliable_event_queue[6][call_id]
			-- When using actors it's possible for multiple Zap clients to exist, but only one called the Zap remote function.
			if thread then
				task.spawn(thread, value)
			end
			reliable_event_queue[6][call_id] = nil
		elseif id == 2 then -- GetPlayerState
			local call_id = buffer.readu8(incoming_buff, read(1))
			local value
			local bool_9 = buffer.readu8(incoming_buff, read(1))
			value = {  }
			value["footyens"] = buffer.readu32(incoming_buff, read(4))
			value["footgems"] = buffer.readu32(incoming_buff, read(4))
			value["totalDistance"] = buffer.readf64(incoming_buff, read(8))
			value["bootsCollected"] = buffer.readu32(incoming_buff, read(4))
			value["activeBoots"] = buffer.readu8(incoming_buff, read(1))
			value["movementSpeedLevel"] = buffer.readu8(incoming_buff, read(1))
			value["studsPerCurrencyLevel"] = buffer.readu8(incoming_buff, read(1))
			value["currencyMultiplierLevel"] = buffer.readu8(incoming_buff, read(1))
			value["bootValueLevel"] = buffer.readu8(incoming_buff, read(1))
			value["spawnRateLevel"] = buffer.readu8(incoming_buff, read(1))
			value["maxActiveBootsLevel"] = buffer.readu8(incoming_buff, read(1))
			value["pickupRadiusLevel"] = buffer.readu8(incoming_buff, read(1))
			value["bootLifetimeLevel"] = buffer.readu8(incoming_buff, read(1))
			value["goldenChanceLevel"] = buffer.readu8(incoming_buff, read(1))
			value["goldenMultiplierLevel"] = buffer.readu8(incoming_buff, read(1))
			value["movementSpeed"] = buffer.readf64(incoming_buff, read(8))
			value["studsPerCurrency"] = buffer.readf64(incoming_buff, read(8))
			value["currencyMultiplier"] = buffer.readf64(incoming_buff, read(8))
			value["bootValue"] = buffer.readf64(incoming_buff, read(8))
			value["bootSpawnInterval"] = buffer.readf64(incoming_buff, read(8))
			value["bootMaxActive"] = buffer.readu8(incoming_buff, read(1))
			value["bootPickupRadius"] = buffer.readf64(incoming_buff, read(8))
			value["bootLifetime"] = buffer.readf64(incoming_buff, read(8))
			value["bootGoldenChance"] = buffer.readf64(incoming_buff, read(8))
			value["bootGoldenMultiplier"] = buffer.readf64(incoming_buff, read(8))
			value["petInventoryLimit"] = buffer.readu8(incoming_buff, read(1))
			value["petEmptySlots"] = buffer.readu8(incoming_buff, read(1))
			value["petInventoryCount"] = buffer.readu8(incoming_buff, read(1))
			value["petEquipLimit"] = buffer.readu8(incoming_buff, read(1))
			value["equippedPetCount"] = buffer.readu8(incoming_buff, read(1))
			value["petFootyenMultiplier"] = buffer.readf64(incoming_buff, read(8))
			value["petPassivePerSecond"] = buffer.readf64(incoming_buff, read(8))
			value["shopHasFootyenGain10x"] = bit32.btest(bool_9, 0b0000000000000001)
			value["shopHasMovementSpeed5x"] = bit32.btest(bool_9, 0b0000000000000010)
			value["shopHasTripleSummon"] = bit32.btest(bool_9, 0b0000000000000100)
			value["shopHasExtraEquipTwo"] = bit32.btest(bool_9, 0b0000000000001000)
			value["shopHasLuckySummon"] = bit32.btest(bool_9, 0b0000000000010000)
			value["shopHasBootMagnet"] = bit32.btest(bool_9, 0b0000000000100000)
			value["shopHasPetPassiveAura"] = bit32.btest(bool_9, 0b0000000001000000)
			value["shopExtraPetSlotsCount"] = buffer.readu16(incoming_buff, read(2))
			value["shopPetPassiveOverclockCount"] = buffer.readu8(incoming_buff, read(1))
			value["shopBootValueCoreCount"] = buffer.readu8(incoming_buff, read(1))
			value["isSprinting"] = bit32.btest(bool_9, 0b0000000010000000)
			value["sprintEndsAt"] = buffer.readf64(incoming_buff, read(8))
			value["cooldownEndsAt"] = buffer.readf64(incoming_buff, read(8))
			local thread = reliable_event_queue[2][call_id]
			-- When using actors it's possible for multiple Zap clients to exist, but only one called the Zap remote function.
			if thread then
				task.spawn(thread, value)
			end
			reliable_event_queue[2][call_id] = nil
		elseif id == 3 then -- GetPetInventory
			local call_id = buffer.readu8(incoming_buff, read(1))
			local value
			value = {  }
			value["petInventoryLimit"] = buffer.readu8(incoming_buff, read(1))
			value["petEmptySlots"] = buffer.readu8(incoming_buff, read(1))
			value["petInventoryCount"] = buffer.readu8(incoming_buff, read(1))
			value["petEquipLimit"] = buffer.readu8(incoming_buff, read(1))
			value["equippedPetCount"] = buffer.readu8(incoming_buff, read(1))
			local len_13 = buffer.readu8(incoming_buff, read(1))
			assert(len_13 <= 45, "value is more than 45!")
			value["pets"] = table.create(len_13)
			for i_3 = 1, len_13 do
				local bool_10 = buffer.readu8(incoming_buff, read(1))
				local val_3
				val_3 = {  }
				local len_14 = buffer.readu8(incoming_buff, read(1))
				assert(len_14 <= 192, "value is more than 192!")
				val_3["uid"] = buffer.readstring(incoming_buff, read(len_14), len_14)
				assert(utf8.len(val_3["uid"]) ~= nil, "value is not valid utf-8")
				local len_15 = buffer.readu8(incoming_buff, read(1))
				assert(len_15 <= 128, "value is more than 128!")
				val_3["petId"] = buffer.readstring(incoming_buff, read(len_15), len_15)
				assert(utf8.len(val_3["petId"]) ~= nil, "value is not valid utf-8")
				val_3["level"] = buffer.readu8(incoming_buff, read(1))
				assert(val_3["level"] >= 1, "value is less than 1!")
				assert(val_3["level"] <= 5, "value is more than 5!")
				val_3["isEquipped"] = bit32.btest(bool_10, 0b0000000000000001)
				value["pets"][i_3] = val_3
			end
			local thread = reliable_event_queue[3][call_id]
			-- When using actors it's possible for multiple Zap clients to exist, but only one called the Zap remote function.
			if thread then
				task.spawn(thread, value)
			end
			reliable_event_queue[3][call_id] = nil
		elseif id == 11 then -- EquipBestPets
			local call_id = buffer.readu8(incoming_buff, read(1))
			local value
			local bool_11 = buffer.readu8(incoming_buff, read(1))
			value = {  }
			value["success"] = bit32.btest(bool_11, 0b0000000000000001)
			local len_16 = buffer.readu16(incoming_buff, read(2))
			assert(len_16 <= 640, "value is more than 640!")
			value["message"] = buffer.readstring(incoming_buff, read(len_16), len_16)
			assert(utf8.len(value["message"]) ~= nil, "value is not valid utf-8")
			local thread = reliable_event_queue[11][call_id]
			-- When using actors it's possible for multiple Zap clients to exist, but only one called the Zap remote function.
			if thread then
				task.spawn(thread, value)
			end
			reliable_event_queue[11][call_id] = nil
		elseif id == 9 then -- DeletePets
			local call_id = buffer.readu8(incoming_buff, read(1))
			local value
			local bool_12 = buffer.readu8(incoming_buff, read(1))
			value = {  }
			value["success"] = bit32.btest(bool_12, 0b0000000000000001)
			local len_17 = buffer.readu16(incoming_buff, read(2))
			assert(len_17 <= 640, "value is more than 640!")
			value["message"] = buffer.readstring(incoming_buff, read(len_17), len_17)
			assert(utf8.len(value["message"]) ~= nil, "value is not valid utf-8")
			local thread = reliable_event_queue[9][call_id]
			-- When using actors it's possible for multiple Zap clients to exist, but only one called the Zap remote function.
			if thread then
				task.spawn(thread, value)
			end
			reliable_event_queue[9][call_id] = nil
		elseif id == 8 then -- DeletePet
			local call_id = buffer.readu8(incoming_buff, read(1))
			local value
			local bool_13 = buffer.readu8(incoming_buff, read(1))
			value = {  }
			value["success"] = bit32.btest(bool_13, 0b0000000000000001)
			local len_18 = buffer.readu16(incoming_buff, read(2))
			assert(len_18 <= 640, "value is more than 640!")
			value["message"] = buffer.readstring(incoming_buff, read(len_18), len_18)
			assert(utf8.len(value["message"]) ~= nil, "value is not valid utf-8")
			local thread = reliable_event_queue[8][call_id]
			-- When using actors it's possible for multiple Zap clients to exist, but only one called the Zap remote function.
			if thread then
				task.spawn(thread, value)
			end
			reliable_event_queue[8][call_id] = nil
		else
			error("Unknown event id")
		end
	end
end)
table.freeze(polling_queues_reliable)
table.freeze(polling_queues_unreliable)

local returns = {
	SendEvents = SendEvents,
	UpgradePet = {
		Call = function(Value: (string)): (({
			["success"]: (boolean),
			["message"]: (string),
		}))
			function_call_id += 1
			function_call_id %= 256
			if reliable_event_queue[10][function_call_id] then
				function_call_id -= 1
				error("Zap has more than 256 calls awaiting a response, and therefore this packet has been dropped")
			end
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, 9)
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, function_call_id)
			local len_19 = #Value
			assert(len_19 <= 192, "value is more than 192!")
			assert(utf8.len(Value) ~= nil, "value is not valid utf-8")
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, len_19)
			alloc(len_19)
			buffer.writestring(outgoing_buff, outgoing_apos, Value, len_19)
			reliable_event_queue[10][function_call_id] = coroutine.running()
			return coroutine.yield()
		end,
	},
	SummonPets = {
		Call = function(Value: ({
			["altarId"]: (string),
			["amount"]: (number),
			["autoDeletePetIds"]: ({ (string) }),
		})): (({
			["success"]: (boolean),
			["message"]: (string),
			["spentFootgems"]: (number),
			["remainingFootgems"]: (number),
			["results"]: ({ ({
				["uid"]: (string),
				["petId"]: (string),
				["rarity"]: (string),
				["level"]: (number),
				["autoDeleted"]: (boolean),
			}) }),
		}))
			function_call_id += 1
			function_call_id %= 256
			if reliable_event_queue[4][function_call_id] then
				function_call_id -= 1
				error("Zap has more than 256 calls awaiting a response, and therefore this packet has been dropped")
			end
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, 3)
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, function_call_id)
			local len_20 = #Value["altarId"]
			assert(len_20 <= 128, "value is more than 128!")
			assert(utf8.len(Value["altarId"]) ~= nil, "value is not valid utf-8")
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, len_20)
			alloc(len_20)
			buffer.writestring(outgoing_buff, outgoing_apos, Value["altarId"], len_20)
			assert(Value["amount"] >= 1, "value is less than 1!")
			assert(Value["amount"] <= 3, "value is more than 3!")
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, Value["amount"])
			local len_21 = #Value["autoDeletePetIds"]
			assert(len_21 <= 6, "value is more than 6!")
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, len_21)
			for i_4 = 1, len_21 do
				local val_4 = Value["autoDeletePetIds"][i_4]
				local len_22 = #val_4
				assert(len_22 <= 128, "value is more than 128!")
				assert(utf8.len(val_4) ~= nil, "value is not valid utf-8")
				alloc(1)
				buffer.writeu8(outgoing_buff, outgoing_apos, len_22)
				alloc(len_22)
				buffer.writestring(outgoing_buff, outgoing_apos, val_4, len_22)
			end
			reliable_event_queue[4][function_call_id] = coroutine.running()
			return coroutine.yield()
		end,
	},
	SetPetEquipped = {
		Call = function(Value: ({
			["uid"]: (string),
			["equipped"]: (boolean),
		})): (({
			["success"]: (boolean),
			["message"]: (string),
		}))
			function_call_id += 1
			function_call_id %= 256
			if reliable_event_queue[7][function_call_id] then
				function_call_id -= 1
				error("Zap has more than 256 calls awaiting a response, and therefore this packet has been dropped")
			end
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, 6)
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, function_call_id)
			local bool_14 = 0
			local bool_14_pos_1 = alloc(1)
			local len_23 = #Value["uid"]
			assert(len_23 <= 192, "value is more than 192!")
			assert(utf8.len(Value["uid"]) ~= nil, "value is not valid utf-8")
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, len_23)
			alloc(len_23)
			buffer.writestring(outgoing_buff, outgoing_apos, Value["uid"], len_23)
			if Value["equipped"] then
				bool_14 = bit32.bor(bool_14, 0b0000000000000001)
			end
			buffer.writeu8(outgoing_buff, bool_14_pos_1, bool_14)
			reliable_event_queue[7][function_call_id] = coroutine.running()
			return coroutine.yield()
		end,
	},
	RequestSprint = {
		Fire = function()
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, 0)
		end,
	},
	PurchaseUpgrade = {
		Call = function(Value: (string)): (({
			["success"]: (boolean),
			["message"]: (string),
		}))
			function_call_id += 1
			function_call_id %= 256
			if reliable_event_queue[5][function_call_id] then
				function_call_id -= 1
				error("Zap has more than 256 calls awaiting a response, and therefore this packet has been dropped")
			end
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, 4)
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, function_call_id)
			local len_24 = #Value
			assert(len_24 <= 128, "value is more than 128!")
			assert(utf8.len(Value) ~= nil, "value is not valid utf-8")
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, len_24)
			alloc(len_24)
			buffer.writestring(outgoing_buff, outgoing_apos, Value, len_24)
			reliable_event_queue[5][function_call_id] = coroutine.running()
			return coroutine.yield()
		end,
	},
	PurchaseBootUpgrade = {
		Call = function(Value: (string)): (({
			["success"]: (boolean),
			["message"]: (string),
		}))
			function_call_id += 1
			function_call_id %= 256
			if reliable_event_queue[6][function_call_id] then
				function_call_id -= 1
				error("Zap has more than 256 calls awaiting a response, and therefore this packet has been dropped")
			end
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, 5)
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, function_call_id)
			local len_25 = #Value
			assert(len_25 <= 128, "value is more than 128!")
			assert(utf8.len(Value) ~= nil, "value is not valid utf-8")
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, len_25)
			alloc(len_25)
			buffer.writestring(outgoing_buff, outgoing_apos, Value, len_25)
			reliable_event_queue[6][function_call_id] = coroutine.running()
			return coroutine.yield()
		end,
	},
	PlayerStateSnapshot = {
		SetCallback = function(Callback: (Value: ({
			["footyens"]: (number),
			["footgems"]: (number),
			["totalDistance"]: (number),
			["bootsCollected"]: (number),
			["activeBoots"]: (number),
			["movementSpeedLevel"]: (number),
			["studsPerCurrencyLevel"]: (number),
			["currencyMultiplierLevel"]: (number),
			["bootValueLevel"]: (number),
			["spawnRateLevel"]: (number),
			["maxActiveBootsLevel"]: (number),
			["pickupRadiusLevel"]: (number),
			["bootLifetimeLevel"]: (number),
			["goldenChanceLevel"]: (number),
			["goldenMultiplierLevel"]: (number),
			["movementSpeed"]: (number),
			["studsPerCurrency"]: (number),
			["currencyMultiplier"]: (number),
			["bootValue"]: (number),
			["bootSpawnInterval"]: (number),
			["bootMaxActive"]: (number),
			["bootPickupRadius"]: (number),
			["bootLifetime"]: (number),
			["bootGoldenChance"]: (number),
			["bootGoldenMultiplier"]: (number),
			["petInventoryLimit"]: (number),
			["petEmptySlots"]: (number),
			["petInventoryCount"]: (number),
			["petEquipLimit"]: (number),
			["equippedPetCount"]: (number),
			["petFootyenMultiplier"]: (number),
			["petPassivePerSecond"]: (number),
			["shopHasFootyenGain10x"]: (boolean),
			["shopHasMovementSpeed5x"]: (boolean),
			["shopHasTripleSummon"]: (boolean),
			["shopHasExtraEquipTwo"]: (boolean),
			["shopHasLuckySummon"]: (boolean),
			["shopHasBootMagnet"]: (boolean),
			["shopHasPetPassiveAura"]: (boolean),
			["shopExtraPetSlotsCount"]: (number),
			["shopPetPassiveOverclockCount"]: (number),
			["shopBootValueCoreCount"]: (number),
			["isSprinting"]: (boolean),
			["sprintEndsAt"]: (number),
			["cooldownEndsAt"]: (number),
		})) -> ()): () -> ()
			reliable_events[0] = Callback
			for _, value in reliable_event_queue[0] do
				task.spawn(Callback, value)
			end
			reliable_event_queue[0] = {}
			return function()
				reliable_events[0] = nil
			end
		end,
	},
	PetInventorySnapshot = {
		SetCallback = function(Callback: (Value: ({
			["petInventoryLimit"]: (number),
			["petEmptySlots"]: (number),
			["petInventoryCount"]: (number),
			["petEquipLimit"]: (number),
			["equippedPetCount"]: (number),
			["pets"]: ({ ({
				["uid"]: (string),
				["petId"]: (string),
				["level"]: (number),
				["isEquipped"]: (boolean),
			}) }),
		})) -> ()): () -> ()
			reliable_events[1] = Callback
			for _, value in reliable_event_queue[1] do
				task.spawn(Callback, value)
			end
			reliable_event_queue[1] = {}
			return function()
				reliable_events[1] = nil
			end
		end,
	},
	GetPlayerState = {
		Call = function(): (({
			["footyens"]: (number),
			["footgems"]: (number),
			["totalDistance"]: (number),
			["bootsCollected"]: (number),
			["activeBoots"]: (number),
			["movementSpeedLevel"]: (number),
			["studsPerCurrencyLevel"]: (number),
			["currencyMultiplierLevel"]: (number),
			["bootValueLevel"]: (number),
			["spawnRateLevel"]: (number),
			["maxActiveBootsLevel"]: (number),
			["pickupRadiusLevel"]: (number),
			["bootLifetimeLevel"]: (number),
			["goldenChanceLevel"]: (number),
			["goldenMultiplierLevel"]: (number),
			["movementSpeed"]: (number),
			["studsPerCurrency"]: (number),
			["currencyMultiplier"]: (number),
			["bootValue"]: (number),
			["bootSpawnInterval"]: (number),
			["bootMaxActive"]: (number),
			["bootPickupRadius"]: (number),
			["bootLifetime"]: (number),
			["bootGoldenChance"]: (number),
			["bootGoldenMultiplier"]: (number),
			["petInventoryLimit"]: (number),
			["petEmptySlots"]: (number),
			["petInventoryCount"]: (number),
			["petEquipLimit"]: (number),
			["equippedPetCount"]: (number),
			["petFootyenMultiplier"]: (number),
			["petPassivePerSecond"]: (number),
			["shopHasFootyenGain10x"]: (boolean),
			["shopHasMovementSpeed5x"]: (boolean),
			["shopHasTripleSummon"]: (boolean),
			["shopHasExtraEquipTwo"]: (boolean),
			["shopHasLuckySummon"]: (boolean),
			["shopHasBootMagnet"]: (boolean),
			["shopHasPetPassiveAura"]: (boolean),
			["shopExtraPetSlotsCount"]: (number),
			["shopPetPassiveOverclockCount"]: (number),
			["shopBootValueCoreCount"]: (number),
			["isSprinting"]: (boolean),
			["sprintEndsAt"]: (number),
			["cooldownEndsAt"]: (number),
		}))
			function_call_id += 1
			function_call_id %= 256
			if reliable_event_queue[2][function_call_id] then
				function_call_id -= 1
				error("Zap has more than 256 calls awaiting a response, and therefore this packet has been dropped")
			end
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, 1)
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, function_call_id)
			reliable_event_queue[2][function_call_id] = coroutine.running()
			return coroutine.yield()
		end,
	},
	GetPetInventory = {
		Call = function(): (({
			["petInventoryLimit"]: (number),
			["petEmptySlots"]: (number),
			["petInventoryCount"]: (number),
			["petEquipLimit"]: (number),
			["equippedPetCount"]: (number),
			["pets"]: ({ ({
				["uid"]: (string),
				["petId"]: (string),
				["level"]: (number),
				["isEquipped"]: (boolean),
			}) }),
		}))
			function_call_id += 1
			function_call_id %= 256
			if reliable_event_queue[3][function_call_id] then
				function_call_id -= 1
				error("Zap has more than 256 calls awaiting a response, and therefore this packet has been dropped")
			end
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, 2)
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, function_call_id)
			reliable_event_queue[3][function_call_id] = coroutine.running()
			return coroutine.yield()
		end,
	},
	EquipBestPets = {
		Call = function(): (({
			["success"]: (boolean),
			["message"]: (string),
		}))
			function_call_id += 1
			function_call_id %= 256
			if reliable_event_queue[11][function_call_id] then
				function_call_id -= 1
				error("Zap has more than 256 calls awaiting a response, and therefore this packet has been dropped")
			end
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, 10)
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, function_call_id)
			reliable_event_queue[11][function_call_id] = coroutine.running()
			return coroutine.yield()
		end,
	},
	DeletePets = {
		Call = function(Value: ({ (string) })): (({
			["success"]: (boolean),
			["message"]: (string),
		}))
			function_call_id += 1
			function_call_id %= 256
			if reliable_event_queue[9][function_call_id] then
				function_call_id -= 1
				error("Zap has more than 256 calls awaiting a response, and therefore this packet has been dropped")
			end
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, 8)
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, function_call_id)
			local len_26 = #Value
			assert(len_26 <= 45, "value is more than 45!")
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, len_26)
			for i_5 = 1, len_26 do
				local val_5 = Value[i_5]
				local len_27 = #val_5
				assert(len_27 <= 192, "value is more than 192!")
				assert(utf8.len(val_5) ~= nil, "value is not valid utf-8")
				alloc(1)
				buffer.writeu8(outgoing_buff, outgoing_apos, len_27)
				alloc(len_27)
				buffer.writestring(outgoing_buff, outgoing_apos, val_5, len_27)
			end
			reliable_event_queue[9][function_call_id] = coroutine.running()
			return coroutine.yield()
		end,
	},
	DeletePet = {
		Call = function(Value: (string)): (({
			["success"]: (boolean),
			["message"]: (string),
		}))
			function_call_id += 1
			function_call_id %= 256
			if reliable_event_queue[8][function_call_id] then
				function_call_id -= 1
				error("Zap has more than 256 calls awaiting a response, and therefore this packet has been dropped")
			end
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, 7)
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, function_call_id)
			local len_28 = #Value
			assert(len_28 <= 192, "value is more than 192!")
			assert(utf8.len(Value) ~= nil, "value is not valid utf-8")
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, len_28)
			alloc(len_28)
			buffer.writestring(outgoing_buff, outgoing_apos, Value, len_28)
			reliable_event_queue[8][function_call_id] = coroutine.running()
			return coroutine.yield()
		end,
	},
}
type Events = typeof(returns)
return returns
