--!native
--!optimize 2
--!nocheck
--!nolint
--#selene: allow(unused_variable, global_usage)
-- Server generated by Zap v0.6.28 (https://github.com/red-blox/zap)
local RunService = game:GetService("RunService")
local ReplicatedStorage = game:GetService("ReplicatedStorage")
local Players = game:GetService("Players")

if RunService:IsClient() then
	error("Cannot use the server module on the client!")
end

if not _G.__ZAP then
	_G.__ZAP = { ["FootyenZap"] = {} }
elseif not _G.__ZAP["FootyenZap"] then
	_G.__ZAP["FootyenZap"] = {}
elseif _G.__ZAP["FootyenZap"]["FOOTYEN"] ~= nil then
	error(`There is already an instance of Zap with the same remote_scope of FOOTYEN, remote_folder of FootyenZap and the version of {_G.__ZAP["FootyenZap"]["FOOTYEN"]}. Change the remote_scope or remote_folder option of both Zap instances`)
end

_G.__ZAP["FootyenZap"]["FOOTYEN"] = "0.6.28"

local outgoing_buff: buffer
local outgoing_used: number
local outgoing_size: number
local outgoing_inst: { Instance }
local outgoing_apos: number
local outgoing_ids: { number }

local incoming_buff: buffer
local incoming_read: number
local incoming_inst: { Instance }
local incoming_ipos: number
local incoming_ids: { number }

-- thanks to https://dom.rojo.space/binary.html#cframe
local CFrameSpecialCases = {
	CFrame.Angles(0, 0, 0),
	CFrame.Angles(math.rad(90), 0, 0),
	CFrame.Angles(0, math.rad(180), math.rad(180)),
	CFrame.Angles(math.rad(-90), 0, 0),
	CFrame.Angles(0, math.rad(180), math.rad(90)),
	CFrame.Angles(0, math.rad(90), math.rad(90)),
	CFrame.Angles(0, 0, math.rad(90)),
	CFrame.Angles(0, math.rad(-90), math.rad(90)),
	CFrame.Angles(math.rad(-90), math.rad(-90), 0),
	CFrame.Angles(0, math.rad(-90), 0),
	CFrame.Angles(math.rad(90), math.rad(-90), 0),
	CFrame.Angles(0, math.rad(90), math.rad(180)),
	CFrame.Angles(0, math.rad(-90), math.rad(180)),
	CFrame.Angles(0, math.rad(180), math.rad(0)),
	CFrame.Angles(math.rad(-90), math.rad(-180), math.rad(0)),
	CFrame.Angles(0, math.rad(0), math.rad(180)),
	CFrame.Angles(math.rad(90), math.rad(180), math.rad(0)),
	CFrame.Angles(0, math.rad(0), math.rad(-90)),
	CFrame.Angles(0, math.rad(-90), math.rad(-90)),
	CFrame.Angles(0, math.rad(-180), math.rad(-90)),
	CFrame.Angles(0, math.rad(90), math.rad(-90)),
	CFrame.Angles(math.rad(90), math.rad(90), 0),
	CFrame.Angles(0, math.rad(90), 0),
	CFrame.Angles(math.rad(-90), math.rad(90), 0),
}

local function alloc(len: number)
	if outgoing_used + len > outgoing_size then
		while outgoing_used + len > outgoing_size do
			outgoing_size = outgoing_size * 2
		end

		local new_buff = buffer.create(outgoing_size)
		buffer.copy(new_buff, 0, outgoing_buff, 0, outgoing_used)

		outgoing_buff = new_buff
	end

	outgoing_apos = outgoing_used
	outgoing_used = outgoing_used + len

	return outgoing_apos
end

local function read(len: number)
	local pos = incoming_read
	incoming_read = incoming_read + len

	return pos
end

local function save()
	return {
		buff = outgoing_buff,
		used = outgoing_used,
		size = outgoing_size,
		inst = outgoing_inst,
		outgoing_ids = outgoing_ids,
		incoming_ids = incoming_ids,
	}
end

local function load(data: {
	buff: buffer,
	used: number,
	size: number,
	inst: { Instance },
	outgoing_ids: { number },
	incoming_ids: { number },
})
	outgoing_buff = data.buff
	outgoing_used = data.used
	outgoing_size = data.size
	outgoing_inst = data.inst
	outgoing_ids = data.outgoing_ids
	incoming_ids = data.incoming_ids
end

local function load_empty()
	outgoing_buff = buffer.create(64)
	outgoing_used = 0
	outgoing_size = 64
	outgoing_inst = {}
	outgoing_ids = {}
	incoming_ids = {}
end

load_empty()

local types = {}

local polling_queues_reliable = {}
local polling_queues_unreliable = {}
if not RunService:IsRunning() then
	local noop = function() end
	return table.freeze({
		SendEvents = noop,
		UpgradePet = table.freeze({
			SetCallback = noop
		}),
		SummonPets = table.freeze({
			SetCallback = noop
		}),
		SetPetEquipped = table.freeze({
			SetCallback = noop
		}),
		RequestSprint = table.freeze({
			SetCallback = noop
		}),
		PurchaseUpgrade = table.freeze({
			SetCallback = noop
		}),
		PurchaseBootUpgrade = table.freeze({
			SetCallback = noop
		}),
		PlayerStateSnapshot = table.freeze({
			Fire = noop,
			FireAll = noop,
			FireExcept = noop,
			FireList = noop,
			FireSet = noop
		}),
		PetInventorySnapshot = table.freeze({
			Fire = noop,
			FireAll = noop,
			FireExcept = noop,
			FireList = noop,
			FireSet = noop
		}),
		GetPlayerState = table.freeze({
			SetCallback = noop
		}),
		GetPetInventory = table.freeze({
			SetCallback = noop
		}),
		EquipBestPets = table.freeze({
			SetCallback = noop
		}),
		DeletePets = table.freeze({
			SetCallback = noop
		}),
		DeletePet = table.freeze({
			SetCallback = noop
		}),
	}) :: Events
end

local remotes = ReplicatedStorage:FindFirstChild("FootyenZap")
if remotes == nil then
	remotes = Instance.new("Folder")
	remotes.Name = "FootyenZap"
	remotes.Parent = ReplicatedStorage
end

local reliable = remotes:FindFirstChild("FOOTYEN_RELIABLE")
if reliable == nil then
	reliable = Instance.new("RemoteEvent")
	reliable.Name = "FOOTYEN_RELIABLE"
	reliable.Parent = remotes
end

local player_map = {}

local function load_player(player: Player)
	if player_map[player] then
		load(player_map[player])
	else
		load_empty()
	end
end

Players.PlayerRemoving:Connect(function(player)
	player_map[player] = nil
end)

local function SendEvents()
	for player, outgoing in player_map do
		if outgoing.used > 0 then
			local buff = buffer.create(outgoing.used)
			buffer.copy(buff, 0, outgoing.buff, 0, outgoing.used)

			reliable:FireClient(player, buff, outgoing.inst)

			outgoing.buff = buffer.create(64)
			outgoing.used = 0
			outgoing.size = 64
			table.clear(outgoing.inst)
		end
	end
end

RunService.Heartbeat:Connect(SendEvents)

local reliable_events = table.create(11)
reliable.OnServerEvent:Connect(function(player, buff, inst)
	incoming_buff = buff
	incoming_inst = inst
	incoming_read = 0
	incoming_ipos = 0
	local len = buffer.len(buff)
	while incoming_read < len do
		local id = buffer.readu8(buff, read(1))
		if id == 0 then -- RequestSprint
			local value
			if reliable_events[0] then
				task.spawn(reliable_events[0], player, value)
			end
		elseif id == 9 then -- UpgradePet
			local call_id = buffer.readu8(buff, read(1))
			local value
			local len_1 = buffer.readu8(incoming_buff, read(1))
			assert(len_1 <= 192, "value is more than 192!")
			value = buffer.readstring(incoming_buff, read(len_1), len_1)
			assert(utf8.len(value) ~= nil, "value is not valid utf-8")
			if reliable_events[9] then
				task.spawn(function(player_2, call_id_2, value_1)
					local ret_1 = reliable_events[9](player_2, value_1)
					load_player(player_2)
					alloc(1)
					buffer.writeu8(outgoing_buff, outgoing_apos, 10)
					alloc(1)
					buffer.writeu8(outgoing_buff, outgoing_apos, call_id_2)
					local bool_1 = 0
					local bool_1_pos_1 = alloc(1)
					if ret_1["success"] then
						bool_1 = bit32.bor(bool_1, 0b0000000000000001)
					end
					local len_2 = #ret_1["message"]
					assert(len_2 <= 640, "value is more than 640!")
					assert(utf8.len(ret_1["message"]) ~= nil, "value is not valid utf-8")
					alloc(2)
					buffer.writeu16(outgoing_buff, outgoing_apos, len_2)
					alloc(len_2)
					buffer.writestring(outgoing_buff, outgoing_apos, ret_1["message"], len_2)
					buffer.writeu8(outgoing_buff, bool_1_pos_1, bool_1)
					player_map[player_2] = save()
				end, player, call_id, value)
			end
		elseif id == 3 then -- SummonPets
			local call_id = buffer.readu8(buff, read(1))
			local value
			value = {  }
			local len_3 = buffer.readu8(incoming_buff, read(1))
			assert(len_3 <= 128, "value is more than 128!")
			value["altarId"] = buffer.readstring(incoming_buff, read(len_3), len_3)
			assert(utf8.len(value["altarId"]) ~= nil, "value is not valid utf-8")
			value["amount"] = buffer.readu8(incoming_buff, read(1))
			assert(value["amount"] >= 1, "value is less than 1!")
			assert(value["amount"] <= 3, "value is more than 3!")
			local len_4 = buffer.readu8(incoming_buff, read(1))
			assert(len_4 <= 6, "value is more than 6!")
			value["autoDeletePetIds"] = table.create(len_4)
			for i_1 = 1, len_4 do
				local val_1
				local len_5 = buffer.readu8(incoming_buff, read(1))
				assert(len_5 <= 128, "value is more than 128!")
				val_1 = buffer.readstring(incoming_buff, read(len_5), len_5)
				assert(utf8.len(val_1) ~= nil, "value is not valid utf-8")
				value["autoDeletePetIds"][i_1] = val_1
			end
			if reliable_events[3] then
				task.spawn(function(player_2, call_id_2, value_1)
					local ret_1 = reliable_events[3](player_2, value_1)
					load_player(player_2)
					alloc(1)
					buffer.writeu8(outgoing_buff, outgoing_apos, 4)
					alloc(1)
					buffer.writeu8(outgoing_buff, outgoing_apos, call_id_2)
					local bool_2 = 0
					local bool_2_pos_1 = alloc(1)
					if ret_1["success"] then
						bool_2 = bit32.bor(bool_2, 0b0000000000000001)
					end
					local len_6 = #ret_1["message"]
					assert(len_6 <= 640, "value is more than 640!")
					assert(utf8.len(ret_1["message"]) ~= nil, "value is not valid utf-8")
					alloc(2)
					buffer.writeu16(outgoing_buff, outgoing_apos, len_6)
					alloc(len_6)
					buffer.writestring(outgoing_buff, outgoing_apos, ret_1["message"], len_6)
					alloc(4)
					buffer.writeu32(outgoing_buff, outgoing_apos, ret_1["spentFootgems"])
					alloc(4)
					buffer.writeu32(outgoing_buff, outgoing_apos, ret_1["remainingFootgems"])
					local len_7 = #ret_1["results"]
					assert(len_7 <= 3, "value is more than 3!")
					alloc(1)
					buffer.writeu8(outgoing_buff, outgoing_apos, len_7)
					for i_2 = 1, len_7 do
						local bool_3 = 0
						local bool_3_pos_1 = alloc(1)
						local val_2 = ret_1["results"][i_2]
						local len_8 = #val_2["uid"]
						assert(len_8 <= 192, "value is more than 192!")
						assert(utf8.len(val_2["uid"]) ~= nil, "value is not valid utf-8")
						alloc(1)
						buffer.writeu8(outgoing_buff, outgoing_apos, len_8)
						alloc(len_8)
						buffer.writestring(outgoing_buff, outgoing_apos, val_2["uid"], len_8)
						local len_9 = #val_2["petId"]
						assert(len_9 <= 128, "value is more than 128!")
						assert(utf8.len(val_2["petId"]) ~= nil, "value is not valid utf-8")
						alloc(1)
						buffer.writeu8(outgoing_buff, outgoing_apos, len_9)
						alloc(len_9)
						buffer.writestring(outgoing_buff, outgoing_apos, val_2["petId"], len_9)
						local len_10 = #val_2["rarity"]
						assert(len_10 <= 64, "value is more than 64!")
						assert(utf8.len(val_2["rarity"]) ~= nil, "value is not valid utf-8")
						alloc(1)
						buffer.writeu8(outgoing_buff, outgoing_apos, len_10)
						alloc(len_10)
						buffer.writestring(outgoing_buff, outgoing_apos, val_2["rarity"], len_10)
						assert(val_2["level"] >= 1, "value is less than 1!")
						assert(val_2["level"] <= 5, "value is more than 5!")
						alloc(1)
						buffer.writeu8(outgoing_buff, outgoing_apos, val_2["level"])
						if val_2["autoDeleted"] then
							bool_3 = bit32.bor(bool_3, 0b0000000000000001)
						end
						buffer.writeu8(outgoing_buff, bool_3_pos_1, bool_3)
					end
					buffer.writeu8(outgoing_buff, bool_2_pos_1, bool_2)
					player_map[player_2] = save()
				end, player, call_id, value)
			end
		elseif id == 6 then -- SetPetEquipped
			local call_id = buffer.readu8(buff, read(1))
			local value
			local bool_4 = buffer.readu8(incoming_buff, read(1))
			value = {  }
			local len_11 = buffer.readu8(incoming_buff, read(1))
			assert(len_11 <= 192, "value is more than 192!")
			value["uid"] = buffer.readstring(incoming_buff, read(len_11), len_11)
			assert(utf8.len(value["uid"]) ~= nil, "value is not valid utf-8")
			value["equipped"] = bit32.btest(bool_4, 0b0000000000000001)
			if reliable_events[6] then
				task.spawn(function(player_2, call_id_2, value_1)
					local ret_1 = reliable_events[6](player_2, value_1)
					load_player(player_2)
					alloc(1)
					buffer.writeu8(outgoing_buff, outgoing_apos, 7)
					alloc(1)
					buffer.writeu8(outgoing_buff, outgoing_apos, call_id_2)
					local bool_5 = 0
					local bool_5_pos_1 = alloc(1)
					if ret_1["success"] then
						bool_5 = bit32.bor(bool_5, 0b0000000000000001)
					end
					local len_12 = #ret_1["message"]
					assert(len_12 <= 640, "value is more than 640!")
					assert(utf8.len(ret_1["message"]) ~= nil, "value is not valid utf-8")
					alloc(2)
					buffer.writeu16(outgoing_buff, outgoing_apos, len_12)
					alloc(len_12)
					buffer.writestring(outgoing_buff, outgoing_apos, ret_1["message"], len_12)
					buffer.writeu8(outgoing_buff, bool_5_pos_1, bool_5)
					player_map[player_2] = save()
				end, player, call_id, value)
			end
		elseif id == 4 then -- PurchaseUpgrade
			local call_id = buffer.readu8(buff, read(1))
			local value
			local len_13 = buffer.readu8(incoming_buff, read(1))
			assert(len_13 <= 128, "value is more than 128!")
			value = buffer.readstring(incoming_buff, read(len_13), len_13)
			assert(utf8.len(value) ~= nil, "value is not valid utf-8")
			if reliable_events[4] then
				task.spawn(function(player_2, call_id_2, value_1)
					local ret_1 = reliable_events[4](player_2, value_1)
					load_player(player_2)
					alloc(1)
					buffer.writeu8(outgoing_buff, outgoing_apos, 5)
					alloc(1)
					buffer.writeu8(outgoing_buff, outgoing_apos, call_id_2)
					local bool_6 = 0
					local bool_6_pos_1 = alloc(1)
					if ret_1["success"] then
						bool_6 = bit32.bor(bool_6, 0b0000000000000001)
					end
					local len_14 = #ret_1["message"]
					assert(len_14 <= 640, "value is more than 640!")
					assert(utf8.len(ret_1["message"]) ~= nil, "value is not valid utf-8")
					alloc(2)
					buffer.writeu16(outgoing_buff, outgoing_apos, len_14)
					alloc(len_14)
					buffer.writestring(outgoing_buff, outgoing_apos, ret_1["message"], len_14)
					buffer.writeu8(outgoing_buff, bool_6_pos_1, bool_6)
					player_map[player_2] = save()
				end, player, call_id, value)
			end
		elseif id == 5 then -- PurchaseBootUpgrade
			local call_id = buffer.readu8(buff, read(1))
			local value
			local len_15 = buffer.readu8(incoming_buff, read(1))
			assert(len_15 <= 128, "value is more than 128!")
			value = buffer.readstring(incoming_buff, read(len_15), len_15)
			assert(utf8.len(value) ~= nil, "value is not valid utf-8")
			if reliable_events[5] then
				task.spawn(function(player_2, call_id_2, value_1)
					local ret_1 = reliable_events[5](player_2, value_1)
					load_player(player_2)
					alloc(1)
					buffer.writeu8(outgoing_buff, outgoing_apos, 6)
					alloc(1)
					buffer.writeu8(outgoing_buff, outgoing_apos, call_id_2)
					local bool_7 = 0
					local bool_7_pos_1 = alloc(1)
					if ret_1["success"] then
						bool_7 = bit32.bor(bool_7, 0b0000000000000001)
					end
					local len_16 = #ret_1["message"]
					assert(len_16 <= 640, "value is more than 640!")
					assert(utf8.len(ret_1["message"]) ~= nil, "value is not valid utf-8")
					alloc(2)
					buffer.writeu16(outgoing_buff, outgoing_apos, len_16)
					alloc(len_16)
					buffer.writestring(outgoing_buff, outgoing_apos, ret_1["message"], len_16)
					buffer.writeu8(outgoing_buff, bool_7_pos_1, bool_7)
					player_map[player_2] = save()
				end, player, call_id, value)
			end
		elseif id == 1 then -- GetPlayerState
			local call_id = buffer.readu8(buff, read(1))
			local value
			if reliable_events[1] then
				task.spawn(function(player_2, call_id_2, value_1)
					local ret_1 = reliable_events[1](player_2, value_1)
					load_player(player_2)
					alloc(1)
					buffer.writeu8(outgoing_buff, outgoing_apos, 2)
					alloc(1)
					buffer.writeu8(outgoing_buff, outgoing_apos, call_id_2)
					local bool_8 = 0
					local bool_8_pos_1 = alloc(1)
					alloc(4)
					buffer.writeu32(outgoing_buff, outgoing_apos, ret_1["footyens"])
					alloc(4)
					buffer.writeu32(outgoing_buff, outgoing_apos, ret_1["footgems"])
					alloc(8)
					buffer.writef64(outgoing_buff, outgoing_apos, ret_1["totalDistance"])
					alloc(4)
					buffer.writeu32(outgoing_buff, outgoing_apos, ret_1["bootsCollected"])
					alloc(1)
					buffer.writeu8(outgoing_buff, outgoing_apos, ret_1["activeBoots"])
					alloc(1)
					buffer.writeu8(outgoing_buff, outgoing_apos, ret_1["movementSpeedLevel"])
					alloc(1)
					buffer.writeu8(outgoing_buff, outgoing_apos, ret_1["studsPerCurrencyLevel"])
					alloc(1)
					buffer.writeu8(outgoing_buff, outgoing_apos, ret_1["currencyMultiplierLevel"])
					alloc(1)
					buffer.writeu8(outgoing_buff, outgoing_apos, ret_1["bootValueLevel"])
					alloc(1)
					buffer.writeu8(outgoing_buff, outgoing_apos, ret_1["spawnRateLevel"])
					alloc(1)
					buffer.writeu8(outgoing_buff, outgoing_apos, ret_1["maxActiveBootsLevel"])
					alloc(1)
					buffer.writeu8(outgoing_buff, outgoing_apos, ret_1["pickupRadiusLevel"])
					alloc(1)
					buffer.writeu8(outgoing_buff, outgoing_apos, ret_1["bootLifetimeLevel"])
					alloc(1)
					buffer.writeu8(outgoing_buff, outgoing_apos, ret_1["goldenChanceLevel"])
					alloc(1)
					buffer.writeu8(outgoing_buff, outgoing_apos, ret_1["goldenMultiplierLevel"])
					alloc(8)
					buffer.writef64(outgoing_buff, outgoing_apos, ret_1["movementSpeed"])
					alloc(8)
					buffer.writef64(outgoing_buff, outgoing_apos, ret_1["studsPerCurrency"])
					alloc(8)
					buffer.writef64(outgoing_buff, outgoing_apos, ret_1["currencyMultiplier"])
					alloc(8)
					buffer.writef64(outgoing_buff, outgoing_apos, ret_1["bootValue"])
					alloc(8)
					buffer.writef64(outgoing_buff, outgoing_apos, ret_1["bootSpawnInterval"])
					alloc(1)
					buffer.writeu8(outgoing_buff, outgoing_apos, ret_1["bootMaxActive"])
					alloc(8)
					buffer.writef64(outgoing_buff, outgoing_apos, ret_1["bootPickupRadius"])
					alloc(8)
					buffer.writef64(outgoing_buff, outgoing_apos, ret_1["bootLifetime"])
					alloc(8)
					buffer.writef64(outgoing_buff, outgoing_apos, ret_1["bootGoldenChance"])
					alloc(8)
					buffer.writef64(outgoing_buff, outgoing_apos, ret_1["bootGoldenMultiplier"])
					alloc(1)
					buffer.writeu8(outgoing_buff, outgoing_apos, ret_1["petInventoryLimit"])
					alloc(1)
					buffer.writeu8(outgoing_buff, outgoing_apos, ret_1["petEmptySlots"])
					alloc(1)
					buffer.writeu8(outgoing_buff, outgoing_apos, ret_1["petInventoryCount"])
					alloc(1)
					buffer.writeu8(outgoing_buff, outgoing_apos, ret_1["petEquipLimit"])
					alloc(1)
					buffer.writeu8(outgoing_buff, outgoing_apos, ret_1["equippedPetCount"])
					alloc(8)
					buffer.writef64(outgoing_buff, outgoing_apos, ret_1["petFootyenMultiplier"])
					alloc(8)
					buffer.writef64(outgoing_buff, outgoing_apos, ret_1["petPassivePerSecond"])
					if ret_1["shopHasFootyenGain10x"] then
						bool_8 = bit32.bor(bool_8, 0b0000000000000001)
					end
					if ret_1["shopHasMovementSpeed5x"] then
						bool_8 = bit32.bor(bool_8, 0b0000000000000010)
					end
					if ret_1["shopHasTripleSummon"] then
						bool_8 = bit32.bor(bool_8, 0b0000000000000100)
					end
					if ret_1["shopHasExtraEquipTwo"] then
						bool_8 = bit32.bor(bool_8, 0b0000000000001000)
					end
					if ret_1["shopHasLuckySummon"] then
						bool_8 = bit32.bor(bool_8, 0b0000000000010000)
					end
					if ret_1["shopHasBootMagnet"] then
						bool_8 = bit32.bor(bool_8, 0b0000000000100000)
					end
					if ret_1["shopHasPetPassiveAura"] then
						bool_8 = bit32.bor(bool_8, 0b0000000001000000)
					end
					alloc(2)
					buffer.writeu16(outgoing_buff, outgoing_apos, ret_1["shopExtraPetSlotsCount"])
					alloc(1)
					buffer.writeu8(outgoing_buff, outgoing_apos, ret_1["shopPetPassiveOverclockCount"])
					alloc(1)
					buffer.writeu8(outgoing_buff, outgoing_apos, ret_1["shopBootValueCoreCount"])
					if ret_1["isSprinting"] then
						bool_8 = bit32.bor(bool_8, 0b0000000010000000)
					end
					alloc(8)
					buffer.writef64(outgoing_buff, outgoing_apos, ret_1["sprintEndsAt"])
					alloc(8)
					buffer.writef64(outgoing_buff, outgoing_apos, ret_1["cooldownEndsAt"])
					buffer.writeu8(outgoing_buff, bool_8_pos_1, bool_8)
					player_map[player_2] = save()
				end, player, call_id, value)
			end
		elseif id == 2 then -- GetPetInventory
			local call_id = buffer.readu8(buff, read(1))
			local value
			if reliable_events[2] then
				task.spawn(function(player_2, call_id_2, value_1)
					local ret_1 = reliable_events[2](player_2, value_1)
					load_player(player_2)
					alloc(1)
					buffer.writeu8(outgoing_buff, outgoing_apos, 3)
					alloc(1)
					buffer.writeu8(outgoing_buff, outgoing_apos, call_id_2)
					alloc(1)
					buffer.writeu8(outgoing_buff, outgoing_apos, ret_1["petInventoryLimit"])
					alloc(1)
					buffer.writeu8(outgoing_buff, outgoing_apos, ret_1["petEmptySlots"])
					alloc(1)
					buffer.writeu8(outgoing_buff, outgoing_apos, ret_1["petInventoryCount"])
					alloc(1)
					buffer.writeu8(outgoing_buff, outgoing_apos, ret_1["petEquipLimit"])
					alloc(1)
					buffer.writeu8(outgoing_buff, outgoing_apos, ret_1["equippedPetCount"])
					local len_17 = #ret_1["pets"]
					assert(len_17 <= 45, "value is more than 45!")
					alloc(1)
					buffer.writeu8(outgoing_buff, outgoing_apos, len_17)
					for i_3 = 1, len_17 do
						local bool_9 = 0
						local bool_9_pos_1 = alloc(1)
						local val_3 = ret_1["pets"][i_3]
						local len_18 = #val_3["uid"]
						assert(len_18 <= 192, "value is more than 192!")
						assert(utf8.len(val_3["uid"]) ~= nil, "value is not valid utf-8")
						alloc(1)
						buffer.writeu8(outgoing_buff, outgoing_apos, len_18)
						alloc(len_18)
						buffer.writestring(outgoing_buff, outgoing_apos, val_3["uid"], len_18)
						local len_19 = #val_3["petId"]
						assert(len_19 <= 128, "value is more than 128!")
						assert(utf8.len(val_3["petId"]) ~= nil, "value is not valid utf-8")
						alloc(1)
						buffer.writeu8(outgoing_buff, outgoing_apos, len_19)
						alloc(len_19)
						buffer.writestring(outgoing_buff, outgoing_apos, val_3["petId"], len_19)
						assert(val_3["level"] >= 1, "value is less than 1!")
						assert(val_3["level"] <= 5, "value is more than 5!")
						alloc(1)
						buffer.writeu8(outgoing_buff, outgoing_apos, val_3["level"])
						if val_3["isEquipped"] then
							bool_9 = bit32.bor(bool_9, 0b0000000000000001)
						end
						buffer.writeu8(outgoing_buff, bool_9_pos_1, bool_9)
					end
					player_map[player_2] = save()
				end, player, call_id, value)
			end
		elseif id == 10 then -- EquipBestPets
			local call_id = buffer.readu8(buff, read(1))
			local value
			if reliable_events[10] then
				task.spawn(function(player_2, call_id_2, value_1)
					local ret_1 = reliable_events[10](player_2, value_1)
					load_player(player_2)
					alloc(1)
					buffer.writeu8(outgoing_buff, outgoing_apos, 11)
					alloc(1)
					buffer.writeu8(outgoing_buff, outgoing_apos, call_id_2)
					local bool_10 = 0
					local bool_10_pos_1 = alloc(1)
					if ret_1["success"] then
						bool_10 = bit32.bor(bool_10, 0b0000000000000001)
					end
					local len_20 = #ret_1["message"]
					assert(len_20 <= 640, "value is more than 640!")
					assert(utf8.len(ret_1["message"]) ~= nil, "value is not valid utf-8")
					alloc(2)
					buffer.writeu16(outgoing_buff, outgoing_apos, len_20)
					alloc(len_20)
					buffer.writestring(outgoing_buff, outgoing_apos, ret_1["message"], len_20)
					buffer.writeu8(outgoing_buff, bool_10_pos_1, bool_10)
					player_map[player_2] = save()
				end, player, call_id, value)
			end
		elseif id == 8 then -- DeletePets
			local call_id = buffer.readu8(buff, read(1))
			local value
			local len_21 = buffer.readu8(incoming_buff, read(1))
			assert(len_21 <= 45, "value is more than 45!")
			value = table.create(len_21)
			for i_4 = 1, len_21 do
				local val_4
				local len_22 = buffer.readu8(incoming_buff, read(1))
				assert(len_22 <= 192, "value is more than 192!")
				val_4 = buffer.readstring(incoming_buff, read(len_22), len_22)
				assert(utf8.len(val_4) ~= nil, "value is not valid utf-8")
				value[i_4] = val_4
			end
			if reliable_events[8] then
				task.spawn(function(player_2, call_id_2, value_1)
					local ret_1 = reliable_events[8](player_2, value_1)
					load_player(player_2)
					alloc(1)
					buffer.writeu8(outgoing_buff, outgoing_apos, 9)
					alloc(1)
					buffer.writeu8(outgoing_buff, outgoing_apos, call_id_2)
					local bool_11 = 0
					local bool_11_pos_1 = alloc(1)
					if ret_1["success"] then
						bool_11 = bit32.bor(bool_11, 0b0000000000000001)
					end
					local len_23 = #ret_1["message"]
					assert(len_23 <= 640, "value is more than 640!")
					assert(utf8.len(ret_1["message"]) ~= nil, "value is not valid utf-8")
					alloc(2)
					buffer.writeu16(outgoing_buff, outgoing_apos, len_23)
					alloc(len_23)
					buffer.writestring(outgoing_buff, outgoing_apos, ret_1["message"], len_23)
					buffer.writeu8(outgoing_buff, bool_11_pos_1, bool_11)
					player_map[player_2] = save()
				end, player, call_id, value)
			end
		elseif id == 7 then -- DeletePet
			local call_id = buffer.readu8(buff, read(1))
			local value
			local len_24 = buffer.readu8(incoming_buff, read(1))
			assert(len_24 <= 192, "value is more than 192!")
			value = buffer.readstring(incoming_buff, read(len_24), len_24)
			assert(utf8.len(value) ~= nil, "value is not valid utf-8")
			if reliable_events[7] then
				task.spawn(function(player_2, call_id_2, value_1)
					local ret_1 = reliable_events[7](player_2, value_1)
					load_player(player_2)
					alloc(1)
					buffer.writeu8(outgoing_buff, outgoing_apos, 8)
					alloc(1)
					buffer.writeu8(outgoing_buff, outgoing_apos, call_id_2)
					local bool_12 = 0
					local bool_12_pos_1 = alloc(1)
					if ret_1["success"] then
						bool_12 = bit32.bor(bool_12, 0b0000000000000001)
					end
					local len_25 = #ret_1["message"]
					assert(len_25 <= 640, "value is more than 640!")
					assert(utf8.len(ret_1["message"]) ~= nil, "value is not valid utf-8")
					alloc(2)
					buffer.writeu16(outgoing_buff, outgoing_apos, len_25)
					alloc(len_25)
					buffer.writestring(outgoing_buff, outgoing_apos, ret_1["message"], len_25)
					buffer.writeu8(outgoing_buff, bool_12_pos_1, bool_12)
					player_map[player_2] = save()
				end, player, call_id, value)
			end
		else
			error("Unknown event id")
		end
	end
end)
table.freeze(polling_queues_reliable)
table.freeze(polling_queues_unreliable)

local returns = {
	SendEvents = SendEvents,
	UpgradePet = {
		SetCallback = function(Callback: (Player: Player, Value: (string)) -> (({
			["success"]: (boolean),
			["message"]: (string),
		}))): () -> ()
			reliable_events[9] = Callback
			return function()
				reliable_events[9] = nil
			end
		end,
	},
	SummonPets = {
		SetCallback = function(Callback: (Player: Player, Value: ({
			["altarId"]: (string),
			["amount"]: (number),
			["autoDeletePetIds"]: ({ (string) }),
		})) -> (({
			["success"]: (boolean),
			["message"]: (string),
			["spentFootgems"]: (number),
			["remainingFootgems"]: (number),
			["results"]: ({ ({
				["uid"]: (string),
				["petId"]: (string),
				["rarity"]: (string),
				["level"]: (number),
				["autoDeleted"]: (boolean),
			}) }),
		}))): () -> ()
			reliable_events[3] = Callback
			return function()
				reliable_events[3] = nil
			end
		end,
	},
	SetPetEquipped = {
		SetCallback = function(Callback: (Player: Player, Value: ({
			["uid"]: (string),
			["equipped"]: (boolean),
		})) -> (({
			["success"]: (boolean),
			["message"]: (string),
		}))): () -> ()
			reliable_events[6] = Callback
			return function()
				reliable_events[6] = nil
			end
		end,
	},
	RequestSprint = {
		SetCallback = function(Callback: (Player: Player) -> ()): () -> ()
			reliable_events[0] = Callback
			return function()
				reliable_events[0] = nil
			end
		end,
	},
	PurchaseUpgrade = {
		SetCallback = function(Callback: (Player: Player, Value: (string)) -> (({
			["success"]: (boolean),
			["message"]: (string),
		}))): () -> ()
			reliable_events[4] = Callback
			return function()
				reliable_events[4] = nil
			end
		end,
	},
	PurchaseBootUpgrade = {
		SetCallback = function(Callback: (Player: Player, Value: (string)) -> (({
			["success"]: (boolean),
			["message"]: (string),
		}))): () -> ()
			reliable_events[5] = Callback
			return function()
				reliable_events[5] = nil
			end
		end,
	},
	PlayerStateSnapshot = {
		Fire = function(Player: Player, Value: ({
			["footyens"]: (number),
			["footgems"]: (number),
			["totalDistance"]: (number),
			["bootsCollected"]: (number),
			["activeBoots"]: (number),
			["movementSpeedLevel"]: (number),
			["studsPerCurrencyLevel"]: (number),
			["currencyMultiplierLevel"]: (number),
			["bootValueLevel"]: (number),
			["spawnRateLevel"]: (number),
			["maxActiveBootsLevel"]: (number),
			["pickupRadiusLevel"]: (number),
			["bootLifetimeLevel"]: (number),
			["goldenChanceLevel"]: (number),
			["goldenMultiplierLevel"]: (number),
			["movementSpeed"]: (number),
			["studsPerCurrency"]: (number),
			["currencyMultiplier"]: (number),
			["bootValue"]: (number),
			["bootSpawnInterval"]: (number),
			["bootMaxActive"]: (number),
			["bootPickupRadius"]: (number),
			["bootLifetime"]: (number),
			["bootGoldenChance"]: (number),
			["bootGoldenMultiplier"]: (number),
			["petInventoryLimit"]: (number),
			["petEmptySlots"]: (number),
			["petInventoryCount"]: (number),
			["petEquipLimit"]: (number),
			["equippedPetCount"]: (number),
			["petFootyenMultiplier"]: (number),
			["petPassivePerSecond"]: (number),
			["shopHasFootyenGain10x"]: (boolean),
			["shopHasMovementSpeed5x"]: (boolean),
			["shopHasTripleSummon"]: (boolean),
			["shopHasExtraEquipTwo"]: (boolean),
			["shopHasLuckySummon"]: (boolean),
			["shopHasBootMagnet"]: (boolean),
			["shopHasPetPassiveAura"]: (boolean),
			["shopExtraPetSlotsCount"]: (number),
			["shopPetPassiveOverclockCount"]: (number),
			["shopBootValueCoreCount"]: (number),
			["isSprinting"]: (boolean),
			["sprintEndsAt"]: (number),
			["cooldownEndsAt"]: (number),
		}))
			load_player(Player)
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, 0)
			local bool_13 = 0
			local bool_13_pos_1 = alloc(1)
			alloc(4)
			buffer.writeu32(outgoing_buff, outgoing_apos, Value["footyens"])
			alloc(4)
			buffer.writeu32(outgoing_buff, outgoing_apos, Value["footgems"])
			alloc(8)
			buffer.writef64(outgoing_buff, outgoing_apos, Value["totalDistance"])
			alloc(4)
			buffer.writeu32(outgoing_buff, outgoing_apos, Value["bootsCollected"])
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, Value["activeBoots"])
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, Value["movementSpeedLevel"])
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, Value["studsPerCurrencyLevel"])
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, Value["currencyMultiplierLevel"])
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, Value["bootValueLevel"])
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, Value["spawnRateLevel"])
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, Value["maxActiveBootsLevel"])
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, Value["pickupRadiusLevel"])
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, Value["bootLifetimeLevel"])
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, Value["goldenChanceLevel"])
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, Value["goldenMultiplierLevel"])
			alloc(8)
			buffer.writef64(outgoing_buff, outgoing_apos, Value["movementSpeed"])
			alloc(8)
			buffer.writef64(outgoing_buff, outgoing_apos, Value["studsPerCurrency"])
			alloc(8)
			buffer.writef64(outgoing_buff, outgoing_apos, Value["currencyMultiplier"])
			alloc(8)
			buffer.writef64(outgoing_buff, outgoing_apos, Value["bootValue"])
			alloc(8)
			buffer.writef64(outgoing_buff, outgoing_apos, Value["bootSpawnInterval"])
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, Value["bootMaxActive"])
			alloc(8)
			buffer.writef64(outgoing_buff, outgoing_apos, Value["bootPickupRadius"])
			alloc(8)
			buffer.writef64(outgoing_buff, outgoing_apos, Value["bootLifetime"])
			alloc(8)
			buffer.writef64(outgoing_buff, outgoing_apos, Value["bootGoldenChance"])
			alloc(8)
			buffer.writef64(outgoing_buff, outgoing_apos, Value["bootGoldenMultiplier"])
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, Value["petInventoryLimit"])
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, Value["petEmptySlots"])
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, Value["petInventoryCount"])
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, Value["petEquipLimit"])
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, Value["equippedPetCount"])
			alloc(8)
			buffer.writef64(outgoing_buff, outgoing_apos, Value["petFootyenMultiplier"])
			alloc(8)
			buffer.writef64(outgoing_buff, outgoing_apos, Value["petPassivePerSecond"])
			if Value["shopHasFootyenGain10x"] then
				bool_13 = bit32.bor(bool_13, 0b0000000000000001)
			end
			if Value["shopHasMovementSpeed5x"] then
				bool_13 = bit32.bor(bool_13, 0b0000000000000010)
			end
			if Value["shopHasTripleSummon"] then
				bool_13 = bit32.bor(bool_13, 0b0000000000000100)
			end
			if Value["shopHasExtraEquipTwo"] then
				bool_13 = bit32.bor(bool_13, 0b0000000000001000)
			end
			if Value["shopHasLuckySummon"] then
				bool_13 = bit32.bor(bool_13, 0b0000000000010000)
			end
			if Value["shopHasBootMagnet"] then
				bool_13 = bit32.bor(bool_13, 0b0000000000100000)
			end
			if Value["shopHasPetPassiveAura"] then
				bool_13 = bit32.bor(bool_13, 0b0000000001000000)
			end
			alloc(2)
			buffer.writeu16(outgoing_buff, outgoing_apos, Value["shopExtraPetSlotsCount"])
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, Value["shopPetPassiveOverclockCount"])
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, Value["shopBootValueCoreCount"])
			if Value["isSprinting"] then
				bool_13 = bit32.bor(bool_13, 0b0000000010000000)
			end
			alloc(8)
			buffer.writef64(outgoing_buff, outgoing_apos, Value["sprintEndsAt"])
			alloc(8)
			buffer.writef64(outgoing_buff, outgoing_apos, Value["cooldownEndsAt"])
			buffer.writeu8(outgoing_buff, bool_13_pos_1, bool_13)
			player_map[Player] = save()
		end,
		FireAll = function(Value: ({
			["footyens"]: (number),
			["footgems"]: (number),
			["totalDistance"]: (number),
			["bootsCollected"]: (number),
			["activeBoots"]: (number),
			["movementSpeedLevel"]: (number),
			["studsPerCurrencyLevel"]: (number),
			["currencyMultiplierLevel"]: (number),
			["bootValueLevel"]: (number),
			["spawnRateLevel"]: (number),
			["maxActiveBootsLevel"]: (number),
			["pickupRadiusLevel"]: (number),
			["bootLifetimeLevel"]: (number),
			["goldenChanceLevel"]: (number),
			["goldenMultiplierLevel"]: (number),
			["movementSpeed"]: (number),
			["studsPerCurrency"]: (number),
			["currencyMultiplier"]: (number),
			["bootValue"]: (number),
			["bootSpawnInterval"]: (number),
			["bootMaxActive"]: (number),
			["bootPickupRadius"]: (number),
			["bootLifetime"]: (number),
			["bootGoldenChance"]: (number),
			["bootGoldenMultiplier"]: (number),
			["petInventoryLimit"]: (number),
			["petEmptySlots"]: (number),
			["petInventoryCount"]: (number),
			["petEquipLimit"]: (number),
			["equippedPetCount"]: (number),
			["petFootyenMultiplier"]: (number),
			["petPassivePerSecond"]: (number),
			["shopHasFootyenGain10x"]: (boolean),
			["shopHasMovementSpeed5x"]: (boolean),
			["shopHasTripleSummon"]: (boolean),
			["shopHasExtraEquipTwo"]: (boolean),
			["shopHasLuckySummon"]: (boolean),
			["shopHasBootMagnet"]: (boolean),
			["shopHasPetPassiveAura"]: (boolean),
			["shopExtraPetSlotsCount"]: (number),
			["shopPetPassiveOverclockCount"]: (number),
			["shopBootValueCoreCount"]: (number),
			["isSprinting"]: (boolean),
			["sprintEndsAt"]: (number),
			["cooldownEndsAt"]: (number),
		}))
			load_empty()
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, 0)
			local bool_14 = 0
			local bool_14_pos_1 = alloc(1)
			alloc(4)
			buffer.writeu32(outgoing_buff, outgoing_apos, Value["footyens"])
			alloc(4)
			buffer.writeu32(outgoing_buff, outgoing_apos, Value["footgems"])
			alloc(8)
			buffer.writef64(outgoing_buff, outgoing_apos, Value["totalDistance"])
			alloc(4)
			buffer.writeu32(outgoing_buff, outgoing_apos, Value["bootsCollected"])
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, Value["activeBoots"])
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, Value["movementSpeedLevel"])
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, Value["studsPerCurrencyLevel"])
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, Value["currencyMultiplierLevel"])
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, Value["bootValueLevel"])
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, Value["spawnRateLevel"])
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, Value["maxActiveBootsLevel"])
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, Value["pickupRadiusLevel"])
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, Value["bootLifetimeLevel"])
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, Value["goldenChanceLevel"])
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, Value["goldenMultiplierLevel"])
			alloc(8)
			buffer.writef64(outgoing_buff, outgoing_apos, Value["movementSpeed"])
			alloc(8)
			buffer.writef64(outgoing_buff, outgoing_apos, Value["studsPerCurrency"])
			alloc(8)
			buffer.writef64(outgoing_buff, outgoing_apos, Value["currencyMultiplier"])
			alloc(8)
			buffer.writef64(outgoing_buff, outgoing_apos, Value["bootValue"])
			alloc(8)
			buffer.writef64(outgoing_buff, outgoing_apos, Value["bootSpawnInterval"])
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, Value["bootMaxActive"])
			alloc(8)
			buffer.writef64(outgoing_buff, outgoing_apos, Value["bootPickupRadius"])
			alloc(8)
			buffer.writef64(outgoing_buff, outgoing_apos, Value["bootLifetime"])
			alloc(8)
			buffer.writef64(outgoing_buff, outgoing_apos, Value["bootGoldenChance"])
			alloc(8)
			buffer.writef64(outgoing_buff, outgoing_apos, Value["bootGoldenMultiplier"])
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, Value["petInventoryLimit"])
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, Value["petEmptySlots"])
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, Value["petInventoryCount"])
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, Value["petEquipLimit"])
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, Value["equippedPetCount"])
			alloc(8)
			buffer.writef64(outgoing_buff, outgoing_apos, Value["petFootyenMultiplier"])
			alloc(8)
			buffer.writef64(outgoing_buff, outgoing_apos, Value["petPassivePerSecond"])
			if Value["shopHasFootyenGain10x"] then
				bool_14 = bit32.bor(bool_14, 0b0000000000000001)
			end
			if Value["shopHasMovementSpeed5x"] then
				bool_14 = bit32.bor(bool_14, 0b0000000000000010)
			end
			if Value["shopHasTripleSummon"] then
				bool_14 = bit32.bor(bool_14, 0b0000000000000100)
			end
			if Value["shopHasExtraEquipTwo"] then
				bool_14 = bit32.bor(bool_14, 0b0000000000001000)
			end
			if Value["shopHasLuckySummon"] then
				bool_14 = bit32.bor(bool_14, 0b0000000000010000)
			end
			if Value["shopHasBootMagnet"] then
				bool_14 = bit32.bor(bool_14, 0b0000000000100000)
			end
			if Value["shopHasPetPassiveAura"] then
				bool_14 = bit32.bor(bool_14, 0b0000000001000000)
			end
			alloc(2)
			buffer.writeu16(outgoing_buff, outgoing_apos, Value["shopExtraPetSlotsCount"])
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, Value["shopPetPassiveOverclockCount"])
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, Value["shopBootValueCoreCount"])
			if Value["isSprinting"] then
				bool_14 = bit32.bor(bool_14, 0b0000000010000000)
			end
			alloc(8)
			buffer.writef64(outgoing_buff, outgoing_apos, Value["sprintEndsAt"])
			alloc(8)
			buffer.writef64(outgoing_buff, outgoing_apos, Value["cooldownEndsAt"])
			buffer.writeu8(outgoing_buff, bool_14_pos_1, bool_14)
			local buff, used, inst = outgoing_buff, outgoing_used, outgoing_inst
			for _, player in Players:GetPlayers() do
				load_player(player)
				alloc(used)
				buffer.copy(outgoing_buff, outgoing_apos, buff, 0, used)
				table.move(inst, 1, #inst, #outgoing_inst + 1, outgoing_inst)
				player_map[player] = save()
			end
		end,
		FireExcept = function(Except: Player, Value: ({
			["footyens"]: (number),
			["footgems"]: (number),
			["totalDistance"]: (number),
			["bootsCollected"]: (number),
			["activeBoots"]: (number),
			["movementSpeedLevel"]: (number),
			["studsPerCurrencyLevel"]: (number),
			["currencyMultiplierLevel"]: (number),
			["bootValueLevel"]: (number),
			["spawnRateLevel"]: (number),
			["maxActiveBootsLevel"]: (number),
			["pickupRadiusLevel"]: (number),
			["bootLifetimeLevel"]: (number),
			["goldenChanceLevel"]: (number),
			["goldenMultiplierLevel"]: (number),
			["movementSpeed"]: (number),
			["studsPerCurrency"]: (number),
			["currencyMultiplier"]: (number),
			["bootValue"]: (number),
			["bootSpawnInterval"]: (number),
			["bootMaxActive"]: (number),
			["bootPickupRadius"]: (number),
			["bootLifetime"]: (number),
			["bootGoldenChance"]: (number),
			["bootGoldenMultiplier"]: (number),
			["petInventoryLimit"]: (number),
			["petEmptySlots"]: (number),
			["petInventoryCount"]: (number),
			["petEquipLimit"]: (number),
			["equippedPetCount"]: (number),
			["petFootyenMultiplier"]: (number),
			["petPassivePerSecond"]: (number),
			["shopHasFootyenGain10x"]: (boolean),
			["shopHasMovementSpeed5x"]: (boolean),
			["shopHasTripleSummon"]: (boolean),
			["shopHasExtraEquipTwo"]: (boolean),
			["shopHasLuckySummon"]: (boolean),
			["shopHasBootMagnet"]: (boolean),
			["shopHasPetPassiveAura"]: (boolean),
			["shopExtraPetSlotsCount"]: (number),
			["shopPetPassiveOverclockCount"]: (number),
			["shopBootValueCoreCount"]: (number),
			["isSprinting"]: (boolean),
			["sprintEndsAt"]: (number),
			["cooldownEndsAt"]: (number),
		}))
			load_empty()
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, 0)
			local bool_15 = 0
			local bool_15_pos_1 = alloc(1)
			alloc(4)
			buffer.writeu32(outgoing_buff, outgoing_apos, Value["footyens"])
			alloc(4)
			buffer.writeu32(outgoing_buff, outgoing_apos, Value["footgems"])
			alloc(8)
			buffer.writef64(outgoing_buff, outgoing_apos, Value["totalDistance"])
			alloc(4)
			buffer.writeu32(outgoing_buff, outgoing_apos, Value["bootsCollected"])
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, Value["activeBoots"])
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, Value["movementSpeedLevel"])
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, Value["studsPerCurrencyLevel"])
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, Value["currencyMultiplierLevel"])
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, Value["bootValueLevel"])
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, Value["spawnRateLevel"])
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, Value["maxActiveBootsLevel"])
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, Value["pickupRadiusLevel"])
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, Value["bootLifetimeLevel"])
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, Value["goldenChanceLevel"])
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, Value["goldenMultiplierLevel"])
			alloc(8)
			buffer.writef64(outgoing_buff, outgoing_apos, Value["movementSpeed"])
			alloc(8)
			buffer.writef64(outgoing_buff, outgoing_apos, Value["studsPerCurrency"])
			alloc(8)
			buffer.writef64(outgoing_buff, outgoing_apos, Value["currencyMultiplier"])
			alloc(8)
			buffer.writef64(outgoing_buff, outgoing_apos, Value["bootValue"])
			alloc(8)
			buffer.writef64(outgoing_buff, outgoing_apos, Value["bootSpawnInterval"])
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, Value["bootMaxActive"])
			alloc(8)
			buffer.writef64(outgoing_buff, outgoing_apos, Value["bootPickupRadius"])
			alloc(8)
			buffer.writef64(outgoing_buff, outgoing_apos, Value["bootLifetime"])
			alloc(8)
			buffer.writef64(outgoing_buff, outgoing_apos, Value["bootGoldenChance"])
			alloc(8)
			buffer.writef64(outgoing_buff, outgoing_apos, Value["bootGoldenMultiplier"])
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, Value["petInventoryLimit"])
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, Value["petEmptySlots"])
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, Value["petInventoryCount"])
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, Value["petEquipLimit"])
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, Value["equippedPetCount"])
			alloc(8)
			buffer.writef64(outgoing_buff, outgoing_apos, Value["petFootyenMultiplier"])
			alloc(8)
			buffer.writef64(outgoing_buff, outgoing_apos, Value["petPassivePerSecond"])
			if Value["shopHasFootyenGain10x"] then
				bool_15 = bit32.bor(bool_15, 0b0000000000000001)
			end
			if Value["shopHasMovementSpeed5x"] then
				bool_15 = bit32.bor(bool_15, 0b0000000000000010)
			end
			if Value["shopHasTripleSummon"] then
				bool_15 = bit32.bor(bool_15, 0b0000000000000100)
			end
			if Value["shopHasExtraEquipTwo"] then
				bool_15 = bit32.bor(bool_15, 0b0000000000001000)
			end
			if Value["shopHasLuckySummon"] then
				bool_15 = bit32.bor(bool_15, 0b0000000000010000)
			end
			if Value["shopHasBootMagnet"] then
				bool_15 = bit32.bor(bool_15, 0b0000000000100000)
			end
			if Value["shopHasPetPassiveAura"] then
				bool_15 = bit32.bor(bool_15, 0b0000000001000000)
			end
			alloc(2)
			buffer.writeu16(outgoing_buff, outgoing_apos, Value["shopExtraPetSlotsCount"])
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, Value["shopPetPassiveOverclockCount"])
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, Value["shopBootValueCoreCount"])
			if Value["isSprinting"] then
				bool_15 = bit32.bor(bool_15, 0b0000000010000000)
			end
			alloc(8)
			buffer.writef64(outgoing_buff, outgoing_apos, Value["sprintEndsAt"])
			alloc(8)
			buffer.writef64(outgoing_buff, outgoing_apos, Value["cooldownEndsAt"])
			buffer.writeu8(outgoing_buff, bool_15_pos_1, bool_15)
			local buff, used, inst = outgoing_buff, outgoing_used, outgoing_inst
			for _, player in Players:GetPlayers() do
				if player ~= Except then
					load_player(player)
					alloc(used)
					buffer.copy(outgoing_buff, outgoing_apos, buff, 0, used)
					table.move(inst, 1, #inst, #outgoing_inst + 1, outgoing_inst)
					player_map[player] = save()
				end
			end
		end,
		FireList = function(List: { [unknown]: Player }, Value: ({
			["footyens"]: (number),
			["footgems"]: (number),
			["totalDistance"]: (number),
			["bootsCollected"]: (number),
			["activeBoots"]: (number),
			["movementSpeedLevel"]: (number),
			["studsPerCurrencyLevel"]: (number),
			["currencyMultiplierLevel"]: (number),
			["bootValueLevel"]: (number),
			["spawnRateLevel"]: (number),
			["maxActiveBootsLevel"]: (number),
			["pickupRadiusLevel"]: (number),
			["bootLifetimeLevel"]: (number),
			["goldenChanceLevel"]: (number),
			["goldenMultiplierLevel"]: (number),
			["movementSpeed"]: (number),
			["studsPerCurrency"]: (number),
			["currencyMultiplier"]: (number),
			["bootValue"]: (number),
			["bootSpawnInterval"]: (number),
			["bootMaxActive"]: (number),
			["bootPickupRadius"]: (number),
			["bootLifetime"]: (number),
			["bootGoldenChance"]: (number),
			["bootGoldenMultiplier"]: (number),
			["petInventoryLimit"]: (number),
			["petEmptySlots"]: (number),
			["petInventoryCount"]: (number),
			["petEquipLimit"]: (number),
			["equippedPetCount"]: (number),
			["petFootyenMultiplier"]: (number),
			["petPassivePerSecond"]: (number),
			["shopHasFootyenGain10x"]: (boolean),
			["shopHasMovementSpeed5x"]: (boolean),
			["shopHasTripleSummon"]: (boolean),
			["shopHasExtraEquipTwo"]: (boolean),
			["shopHasLuckySummon"]: (boolean),
			["shopHasBootMagnet"]: (boolean),
			["shopHasPetPassiveAura"]: (boolean),
			["shopExtraPetSlotsCount"]: (number),
			["shopPetPassiveOverclockCount"]: (number),
			["shopBootValueCoreCount"]: (number),
			["isSprinting"]: (boolean),
			["sprintEndsAt"]: (number),
			["cooldownEndsAt"]: (number),
		}))
			load_empty()
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, 0)
			local bool_16 = 0
			local bool_16_pos_1 = alloc(1)
			alloc(4)
			buffer.writeu32(outgoing_buff, outgoing_apos, Value["footyens"])
			alloc(4)
			buffer.writeu32(outgoing_buff, outgoing_apos, Value["footgems"])
			alloc(8)
			buffer.writef64(outgoing_buff, outgoing_apos, Value["totalDistance"])
			alloc(4)
			buffer.writeu32(outgoing_buff, outgoing_apos, Value["bootsCollected"])
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, Value["activeBoots"])
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, Value["movementSpeedLevel"])
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, Value["studsPerCurrencyLevel"])
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, Value["currencyMultiplierLevel"])
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, Value["bootValueLevel"])
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, Value["spawnRateLevel"])
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, Value["maxActiveBootsLevel"])
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, Value["pickupRadiusLevel"])
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, Value["bootLifetimeLevel"])
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, Value["goldenChanceLevel"])
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, Value["goldenMultiplierLevel"])
			alloc(8)
			buffer.writef64(outgoing_buff, outgoing_apos, Value["movementSpeed"])
			alloc(8)
			buffer.writef64(outgoing_buff, outgoing_apos, Value["studsPerCurrency"])
			alloc(8)
			buffer.writef64(outgoing_buff, outgoing_apos, Value["currencyMultiplier"])
			alloc(8)
			buffer.writef64(outgoing_buff, outgoing_apos, Value["bootValue"])
			alloc(8)
			buffer.writef64(outgoing_buff, outgoing_apos, Value["bootSpawnInterval"])
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, Value["bootMaxActive"])
			alloc(8)
			buffer.writef64(outgoing_buff, outgoing_apos, Value["bootPickupRadius"])
			alloc(8)
			buffer.writef64(outgoing_buff, outgoing_apos, Value["bootLifetime"])
			alloc(8)
			buffer.writef64(outgoing_buff, outgoing_apos, Value["bootGoldenChance"])
			alloc(8)
			buffer.writef64(outgoing_buff, outgoing_apos, Value["bootGoldenMultiplier"])
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, Value["petInventoryLimit"])
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, Value["petEmptySlots"])
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, Value["petInventoryCount"])
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, Value["petEquipLimit"])
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, Value["equippedPetCount"])
			alloc(8)
			buffer.writef64(outgoing_buff, outgoing_apos, Value["petFootyenMultiplier"])
			alloc(8)
			buffer.writef64(outgoing_buff, outgoing_apos, Value["petPassivePerSecond"])
			if Value["shopHasFootyenGain10x"] then
				bool_16 = bit32.bor(bool_16, 0b0000000000000001)
			end
			if Value["shopHasMovementSpeed5x"] then
				bool_16 = bit32.bor(bool_16, 0b0000000000000010)
			end
			if Value["shopHasTripleSummon"] then
				bool_16 = bit32.bor(bool_16, 0b0000000000000100)
			end
			if Value["shopHasExtraEquipTwo"] then
				bool_16 = bit32.bor(bool_16, 0b0000000000001000)
			end
			if Value["shopHasLuckySummon"] then
				bool_16 = bit32.bor(bool_16, 0b0000000000010000)
			end
			if Value["shopHasBootMagnet"] then
				bool_16 = bit32.bor(bool_16, 0b0000000000100000)
			end
			if Value["shopHasPetPassiveAura"] then
				bool_16 = bit32.bor(bool_16, 0b0000000001000000)
			end
			alloc(2)
			buffer.writeu16(outgoing_buff, outgoing_apos, Value["shopExtraPetSlotsCount"])
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, Value["shopPetPassiveOverclockCount"])
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, Value["shopBootValueCoreCount"])
			if Value["isSprinting"] then
				bool_16 = bit32.bor(bool_16, 0b0000000010000000)
			end
			alloc(8)
			buffer.writef64(outgoing_buff, outgoing_apos, Value["sprintEndsAt"])
			alloc(8)
			buffer.writef64(outgoing_buff, outgoing_apos, Value["cooldownEndsAt"])
			buffer.writeu8(outgoing_buff, bool_16_pos_1, bool_16)
			local buff, used, inst = outgoing_buff, outgoing_used, outgoing_inst
			for _, player in List do
				load_player(player)
				alloc(used)
				buffer.copy(outgoing_buff, outgoing_apos, buff, 0, used)
				table.move(inst, 1, #inst, #outgoing_inst + 1, outgoing_inst)
				player_map[player] = save()
			end
		end,
		FireSet = function(Set: { [Player]: any }, Value: ({
			["footyens"]: (number),
			["footgems"]: (number),
			["totalDistance"]: (number),
			["bootsCollected"]: (number),
			["activeBoots"]: (number),
			["movementSpeedLevel"]: (number),
			["studsPerCurrencyLevel"]: (number),
			["currencyMultiplierLevel"]: (number),
			["bootValueLevel"]: (number),
			["spawnRateLevel"]: (number),
			["maxActiveBootsLevel"]: (number),
			["pickupRadiusLevel"]: (number),
			["bootLifetimeLevel"]: (number),
			["goldenChanceLevel"]: (number),
			["goldenMultiplierLevel"]: (number),
			["movementSpeed"]: (number),
			["studsPerCurrency"]: (number),
			["currencyMultiplier"]: (number),
			["bootValue"]: (number),
			["bootSpawnInterval"]: (number),
			["bootMaxActive"]: (number),
			["bootPickupRadius"]: (number),
			["bootLifetime"]: (number),
			["bootGoldenChance"]: (number),
			["bootGoldenMultiplier"]: (number),
			["petInventoryLimit"]: (number),
			["petEmptySlots"]: (number),
			["petInventoryCount"]: (number),
			["petEquipLimit"]: (number),
			["equippedPetCount"]: (number),
			["petFootyenMultiplier"]: (number),
			["petPassivePerSecond"]: (number),
			["shopHasFootyenGain10x"]: (boolean),
			["shopHasMovementSpeed5x"]: (boolean),
			["shopHasTripleSummon"]: (boolean),
			["shopHasExtraEquipTwo"]: (boolean),
			["shopHasLuckySummon"]: (boolean),
			["shopHasBootMagnet"]: (boolean),
			["shopHasPetPassiveAura"]: (boolean),
			["shopExtraPetSlotsCount"]: (number),
			["shopPetPassiveOverclockCount"]: (number),
			["shopBootValueCoreCount"]: (number),
			["isSprinting"]: (boolean),
			["sprintEndsAt"]: (number),
			["cooldownEndsAt"]: (number),
		}))
			load_empty()
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, 0)
			local bool_17 = 0
			local bool_17_pos_1 = alloc(1)
			alloc(4)
			buffer.writeu32(outgoing_buff, outgoing_apos, Value["footyens"])
			alloc(4)
			buffer.writeu32(outgoing_buff, outgoing_apos, Value["footgems"])
			alloc(8)
			buffer.writef64(outgoing_buff, outgoing_apos, Value["totalDistance"])
			alloc(4)
			buffer.writeu32(outgoing_buff, outgoing_apos, Value["bootsCollected"])
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, Value["activeBoots"])
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, Value["movementSpeedLevel"])
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, Value["studsPerCurrencyLevel"])
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, Value["currencyMultiplierLevel"])
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, Value["bootValueLevel"])
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, Value["spawnRateLevel"])
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, Value["maxActiveBootsLevel"])
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, Value["pickupRadiusLevel"])
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, Value["bootLifetimeLevel"])
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, Value["goldenChanceLevel"])
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, Value["goldenMultiplierLevel"])
			alloc(8)
			buffer.writef64(outgoing_buff, outgoing_apos, Value["movementSpeed"])
			alloc(8)
			buffer.writef64(outgoing_buff, outgoing_apos, Value["studsPerCurrency"])
			alloc(8)
			buffer.writef64(outgoing_buff, outgoing_apos, Value["currencyMultiplier"])
			alloc(8)
			buffer.writef64(outgoing_buff, outgoing_apos, Value["bootValue"])
			alloc(8)
			buffer.writef64(outgoing_buff, outgoing_apos, Value["bootSpawnInterval"])
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, Value["bootMaxActive"])
			alloc(8)
			buffer.writef64(outgoing_buff, outgoing_apos, Value["bootPickupRadius"])
			alloc(8)
			buffer.writef64(outgoing_buff, outgoing_apos, Value["bootLifetime"])
			alloc(8)
			buffer.writef64(outgoing_buff, outgoing_apos, Value["bootGoldenChance"])
			alloc(8)
			buffer.writef64(outgoing_buff, outgoing_apos, Value["bootGoldenMultiplier"])
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, Value["petInventoryLimit"])
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, Value["petEmptySlots"])
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, Value["petInventoryCount"])
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, Value["petEquipLimit"])
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, Value["equippedPetCount"])
			alloc(8)
			buffer.writef64(outgoing_buff, outgoing_apos, Value["petFootyenMultiplier"])
			alloc(8)
			buffer.writef64(outgoing_buff, outgoing_apos, Value["petPassivePerSecond"])
			if Value["shopHasFootyenGain10x"] then
				bool_17 = bit32.bor(bool_17, 0b0000000000000001)
			end
			if Value["shopHasMovementSpeed5x"] then
				bool_17 = bit32.bor(bool_17, 0b0000000000000010)
			end
			if Value["shopHasTripleSummon"] then
				bool_17 = bit32.bor(bool_17, 0b0000000000000100)
			end
			if Value["shopHasExtraEquipTwo"] then
				bool_17 = bit32.bor(bool_17, 0b0000000000001000)
			end
			if Value["shopHasLuckySummon"] then
				bool_17 = bit32.bor(bool_17, 0b0000000000010000)
			end
			if Value["shopHasBootMagnet"] then
				bool_17 = bit32.bor(bool_17, 0b0000000000100000)
			end
			if Value["shopHasPetPassiveAura"] then
				bool_17 = bit32.bor(bool_17, 0b0000000001000000)
			end
			alloc(2)
			buffer.writeu16(outgoing_buff, outgoing_apos, Value["shopExtraPetSlotsCount"])
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, Value["shopPetPassiveOverclockCount"])
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, Value["shopBootValueCoreCount"])
			if Value["isSprinting"] then
				bool_17 = bit32.bor(bool_17, 0b0000000010000000)
			end
			alloc(8)
			buffer.writef64(outgoing_buff, outgoing_apos, Value["sprintEndsAt"])
			alloc(8)
			buffer.writef64(outgoing_buff, outgoing_apos, Value["cooldownEndsAt"])
			buffer.writeu8(outgoing_buff, bool_17_pos_1, bool_17)
			local buff, used, inst = outgoing_buff, outgoing_used, outgoing_inst
			for player in Set do
				load_player(player)
				alloc(used)
				buffer.copy(outgoing_buff, outgoing_apos, buff, 0, used)
				table.move(inst, 1, #inst, #outgoing_inst + 1, outgoing_inst)
				player_map[player] = save()
			end
		end,
	},
	PetInventorySnapshot = {
		Fire = function(Player: Player, Value: ({
			["petInventoryLimit"]: (number),
			["petEmptySlots"]: (number),
			["petInventoryCount"]: (number),
			["petEquipLimit"]: (number),
			["equippedPetCount"]: (number),
			["pets"]: ({ ({
				["uid"]: (string),
				["petId"]: (string),
				["level"]: (number),
				["isEquipped"]: (boolean),
			}) }),
		}))
			load_player(Player)
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, 1)
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, Value["petInventoryLimit"])
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, Value["petEmptySlots"])
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, Value["petInventoryCount"])
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, Value["petEquipLimit"])
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, Value["equippedPetCount"])
			local len_26 = #Value["pets"]
			assert(len_26 <= 45, "value is more than 45!")
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, len_26)
			for i_5 = 1, len_26 do
				local bool_18 = 0
				local bool_18_pos_1 = alloc(1)
				local val_5 = Value["pets"][i_5]
				local len_27 = #val_5["uid"]
				assert(len_27 <= 192, "value is more than 192!")
				assert(utf8.len(val_5["uid"]) ~= nil, "value is not valid utf-8")
				alloc(1)
				buffer.writeu8(outgoing_buff, outgoing_apos, len_27)
				alloc(len_27)
				buffer.writestring(outgoing_buff, outgoing_apos, val_5["uid"], len_27)
				local len_28 = #val_5["petId"]
				assert(len_28 <= 128, "value is more than 128!")
				assert(utf8.len(val_5["petId"]) ~= nil, "value is not valid utf-8")
				alloc(1)
				buffer.writeu8(outgoing_buff, outgoing_apos, len_28)
				alloc(len_28)
				buffer.writestring(outgoing_buff, outgoing_apos, val_5["petId"], len_28)
				assert(val_5["level"] >= 1, "value is less than 1!")
				assert(val_5["level"] <= 5, "value is more than 5!")
				alloc(1)
				buffer.writeu8(outgoing_buff, outgoing_apos, val_5["level"])
				if val_5["isEquipped"] then
					bool_18 = bit32.bor(bool_18, 0b0000000000000001)
				end
				buffer.writeu8(outgoing_buff, bool_18_pos_1, bool_18)
			end
			player_map[Player] = save()
		end,
		FireAll = function(Value: ({
			["petInventoryLimit"]: (number),
			["petEmptySlots"]: (number),
			["petInventoryCount"]: (number),
			["petEquipLimit"]: (number),
			["equippedPetCount"]: (number),
			["pets"]: ({ ({
				["uid"]: (string),
				["petId"]: (string),
				["level"]: (number),
				["isEquipped"]: (boolean),
			}) }),
		}))
			load_empty()
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, 1)
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, Value["petInventoryLimit"])
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, Value["petEmptySlots"])
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, Value["petInventoryCount"])
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, Value["petEquipLimit"])
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, Value["equippedPetCount"])
			local len_29 = #Value["pets"]
			assert(len_29 <= 45, "value is more than 45!")
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, len_29)
			for i_6 = 1, len_29 do
				local bool_19 = 0
				local bool_19_pos_1 = alloc(1)
				local val_6 = Value["pets"][i_6]
				local len_30 = #val_6["uid"]
				assert(len_30 <= 192, "value is more than 192!")
				assert(utf8.len(val_6["uid"]) ~= nil, "value is not valid utf-8")
				alloc(1)
				buffer.writeu8(outgoing_buff, outgoing_apos, len_30)
				alloc(len_30)
				buffer.writestring(outgoing_buff, outgoing_apos, val_6["uid"], len_30)
				local len_31 = #val_6["petId"]
				assert(len_31 <= 128, "value is more than 128!")
				assert(utf8.len(val_6["petId"]) ~= nil, "value is not valid utf-8")
				alloc(1)
				buffer.writeu8(outgoing_buff, outgoing_apos, len_31)
				alloc(len_31)
				buffer.writestring(outgoing_buff, outgoing_apos, val_6["petId"], len_31)
				assert(val_6["level"] >= 1, "value is less than 1!")
				assert(val_6["level"] <= 5, "value is more than 5!")
				alloc(1)
				buffer.writeu8(outgoing_buff, outgoing_apos, val_6["level"])
				if val_6["isEquipped"] then
					bool_19 = bit32.bor(bool_19, 0b0000000000000001)
				end
				buffer.writeu8(outgoing_buff, bool_19_pos_1, bool_19)
			end
			local buff, used, inst = outgoing_buff, outgoing_used, outgoing_inst
			for _, player in Players:GetPlayers() do
				load_player(player)
				alloc(used)
				buffer.copy(outgoing_buff, outgoing_apos, buff, 0, used)
				table.move(inst, 1, #inst, #outgoing_inst + 1, outgoing_inst)
				player_map[player] = save()
			end
		end,
		FireExcept = function(Except: Player, Value: ({
			["petInventoryLimit"]: (number),
			["petEmptySlots"]: (number),
			["petInventoryCount"]: (number),
			["petEquipLimit"]: (number),
			["equippedPetCount"]: (number),
			["pets"]: ({ ({
				["uid"]: (string),
				["petId"]: (string),
				["level"]: (number),
				["isEquipped"]: (boolean),
			}) }),
		}))
			load_empty()
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, 1)
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, Value["petInventoryLimit"])
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, Value["petEmptySlots"])
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, Value["petInventoryCount"])
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, Value["petEquipLimit"])
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, Value["equippedPetCount"])
			local len_32 = #Value["pets"]
			assert(len_32 <= 45, "value is more than 45!")
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, len_32)
			for i_7 = 1, len_32 do
				local bool_20 = 0
				local bool_20_pos_1 = alloc(1)
				local val_7 = Value["pets"][i_7]
				local len_33 = #val_7["uid"]
				assert(len_33 <= 192, "value is more than 192!")
				assert(utf8.len(val_7["uid"]) ~= nil, "value is not valid utf-8")
				alloc(1)
				buffer.writeu8(outgoing_buff, outgoing_apos, len_33)
				alloc(len_33)
				buffer.writestring(outgoing_buff, outgoing_apos, val_7["uid"], len_33)
				local len_34 = #val_7["petId"]
				assert(len_34 <= 128, "value is more than 128!")
				assert(utf8.len(val_7["petId"]) ~= nil, "value is not valid utf-8")
				alloc(1)
				buffer.writeu8(outgoing_buff, outgoing_apos, len_34)
				alloc(len_34)
				buffer.writestring(outgoing_buff, outgoing_apos, val_7["petId"], len_34)
				assert(val_7["level"] >= 1, "value is less than 1!")
				assert(val_7["level"] <= 5, "value is more than 5!")
				alloc(1)
				buffer.writeu8(outgoing_buff, outgoing_apos, val_7["level"])
				if val_7["isEquipped"] then
					bool_20 = bit32.bor(bool_20, 0b0000000000000001)
				end
				buffer.writeu8(outgoing_buff, bool_20_pos_1, bool_20)
			end
			local buff, used, inst = outgoing_buff, outgoing_used, outgoing_inst
			for _, player in Players:GetPlayers() do
				if player ~= Except then
					load_player(player)
					alloc(used)
					buffer.copy(outgoing_buff, outgoing_apos, buff, 0, used)
					table.move(inst, 1, #inst, #outgoing_inst + 1, outgoing_inst)
					player_map[player] = save()
				end
			end
		end,
		FireList = function(List: { [unknown]: Player }, Value: ({
			["petInventoryLimit"]: (number),
			["petEmptySlots"]: (number),
			["petInventoryCount"]: (number),
			["petEquipLimit"]: (number),
			["equippedPetCount"]: (number),
			["pets"]: ({ ({
				["uid"]: (string),
				["petId"]: (string),
				["level"]: (number),
				["isEquipped"]: (boolean),
			}) }),
		}))
			load_empty()
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, 1)
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, Value["petInventoryLimit"])
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, Value["petEmptySlots"])
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, Value["petInventoryCount"])
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, Value["petEquipLimit"])
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, Value["equippedPetCount"])
			local len_35 = #Value["pets"]
			assert(len_35 <= 45, "value is more than 45!")
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, len_35)
			for i_8 = 1, len_35 do
				local bool_21 = 0
				local bool_21_pos_1 = alloc(1)
				local val_8 = Value["pets"][i_8]
				local len_36 = #val_8["uid"]
				assert(len_36 <= 192, "value is more than 192!")
				assert(utf8.len(val_8["uid"]) ~= nil, "value is not valid utf-8")
				alloc(1)
				buffer.writeu8(outgoing_buff, outgoing_apos, len_36)
				alloc(len_36)
				buffer.writestring(outgoing_buff, outgoing_apos, val_8["uid"], len_36)
				local len_37 = #val_8["petId"]
				assert(len_37 <= 128, "value is more than 128!")
				assert(utf8.len(val_8["petId"]) ~= nil, "value is not valid utf-8")
				alloc(1)
				buffer.writeu8(outgoing_buff, outgoing_apos, len_37)
				alloc(len_37)
				buffer.writestring(outgoing_buff, outgoing_apos, val_8["petId"], len_37)
				assert(val_8["level"] >= 1, "value is less than 1!")
				assert(val_8["level"] <= 5, "value is more than 5!")
				alloc(1)
				buffer.writeu8(outgoing_buff, outgoing_apos, val_8["level"])
				if val_8["isEquipped"] then
					bool_21 = bit32.bor(bool_21, 0b0000000000000001)
				end
				buffer.writeu8(outgoing_buff, bool_21_pos_1, bool_21)
			end
			local buff, used, inst = outgoing_buff, outgoing_used, outgoing_inst
			for _, player in List do
				load_player(player)
				alloc(used)
				buffer.copy(outgoing_buff, outgoing_apos, buff, 0, used)
				table.move(inst, 1, #inst, #outgoing_inst + 1, outgoing_inst)
				player_map[player] = save()
			end
		end,
		FireSet = function(Set: { [Player]: any }, Value: ({
			["petInventoryLimit"]: (number),
			["petEmptySlots"]: (number),
			["petInventoryCount"]: (number),
			["petEquipLimit"]: (number),
			["equippedPetCount"]: (number),
			["pets"]: ({ ({
				["uid"]: (string),
				["petId"]: (string),
				["level"]: (number),
				["isEquipped"]: (boolean),
			}) }),
		}))
			load_empty()
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, 1)
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, Value["petInventoryLimit"])
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, Value["petEmptySlots"])
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, Value["petInventoryCount"])
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, Value["petEquipLimit"])
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, Value["equippedPetCount"])
			local len_38 = #Value["pets"]
			assert(len_38 <= 45, "value is more than 45!")
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, len_38)
			for i_9 = 1, len_38 do
				local bool_22 = 0
				local bool_22_pos_1 = alloc(1)
				local val_9 = Value["pets"][i_9]
				local len_39 = #val_9["uid"]
				assert(len_39 <= 192, "value is more than 192!")
				assert(utf8.len(val_9["uid"]) ~= nil, "value is not valid utf-8")
				alloc(1)
				buffer.writeu8(outgoing_buff, outgoing_apos, len_39)
				alloc(len_39)
				buffer.writestring(outgoing_buff, outgoing_apos, val_9["uid"], len_39)
				local len_40 = #val_9["petId"]
				assert(len_40 <= 128, "value is more than 128!")
				assert(utf8.len(val_9["petId"]) ~= nil, "value is not valid utf-8")
				alloc(1)
				buffer.writeu8(outgoing_buff, outgoing_apos, len_40)
				alloc(len_40)
				buffer.writestring(outgoing_buff, outgoing_apos, val_9["petId"], len_40)
				assert(val_9["level"] >= 1, "value is less than 1!")
				assert(val_9["level"] <= 5, "value is more than 5!")
				alloc(1)
				buffer.writeu8(outgoing_buff, outgoing_apos, val_9["level"])
				if val_9["isEquipped"] then
					bool_22 = bit32.bor(bool_22, 0b0000000000000001)
				end
				buffer.writeu8(outgoing_buff, bool_22_pos_1, bool_22)
			end
			local buff, used, inst = outgoing_buff, outgoing_used, outgoing_inst
			for player in Set do
				load_player(player)
				alloc(used)
				buffer.copy(outgoing_buff, outgoing_apos, buff, 0, used)
				table.move(inst, 1, #inst, #outgoing_inst + 1, outgoing_inst)
				player_map[player] = save()
			end
		end,
	},
	GetPlayerState = {
		SetCallback = function(Callback: (Player: Player) -> (({
			["footyens"]: (number),
			["footgems"]: (number),
			["totalDistance"]: (number),
			["bootsCollected"]: (number),
			["activeBoots"]: (number),
			["movementSpeedLevel"]: (number),
			["studsPerCurrencyLevel"]: (number),
			["currencyMultiplierLevel"]: (number),
			["bootValueLevel"]: (number),
			["spawnRateLevel"]: (number),
			["maxActiveBootsLevel"]: (number),
			["pickupRadiusLevel"]: (number),
			["bootLifetimeLevel"]: (number),
			["goldenChanceLevel"]: (number),
			["goldenMultiplierLevel"]: (number),
			["movementSpeed"]: (number),
			["studsPerCurrency"]: (number),
			["currencyMultiplier"]: (number),
			["bootValue"]: (number),
			["bootSpawnInterval"]: (number),
			["bootMaxActive"]: (number),
			["bootPickupRadius"]: (number),
			["bootLifetime"]: (number),
			["bootGoldenChance"]: (number),
			["bootGoldenMultiplier"]: (number),
			["petInventoryLimit"]: (number),
			["petEmptySlots"]: (number),
			["petInventoryCount"]: (number),
			["petEquipLimit"]: (number),
			["equippedPetCount"]: (number),
			["petFootyenMultiplier"]: (number),
			["petPassivePerSecond"]: (number),
			["shopHasFootyenGain10x"]: (boolean),
			["shopHasMovementSpeed5x"]: (boolean),
			["shopHasTripleSummon"]: (boolean),
			["shopHasExtraEquipTwo"]: (boolean),
			["shopHasLuckySummon"]: (boolean),
			["shopHasBootMagnet"]: (boolean),
			["shopHasPetPassiveAura"]: (boolean),
			["shopExtraPetSlotsCount"]: (number),
			["shopPetPassiveOverclockCount"]: (number),
			["shopBootValueCoreCount"]: (number),
			["isSprinting"]: (boolean),
			["sprintEndsAt"]: (number),
			["cooldownEndsAt"]: (number),
		}))): () -> ()
			reliable_events[1] = Callback
			return function()
				reliable_events[1] = nil
			end
		end,
	},
	GetPetInventory = {
		SetCallback = function(Callback: (Player: Player) -> (({
			["petInventoryLimit"]: (number),
			["petEmptySlots"]: (number),
			["petInventoryCount"]: (number),
			["petEquipLimit"]: (number),
			["equippedPetCount"]: (number),
			["pets"]: ({ ({
				["uid"]: (string),
				["petId"]: (string),
				["level"]: (number),
				["isEquipped"]: (boolean),
			}) }),
		}))): () -> ()
			reliable_events[2] = Callback
			return function()
				reliable_events[2] = nil
			end
		end,
	},
	EquipBestPets = {
		SetCallback = function(Callback: (Player: Player) -> (({
			["success"]: (boolean),
			["message"]: (string),
		}))): () -> ()
			reliable_events[10] = Callback
			return function()
				reliable_events[10] = nil
			end
		end,
	},
	DeletePets = {
		SetCallback = function(Callback: (Player: Player, Value: ({ (string) })) -> (({
			["success"]: (boolean),
			["message"]: (string),
		}))): () -> ()
			reliable_events[8] = Callback
			return function()
				reliable_events[8] = nil
			end
		end,
	},
	DeletePet = {
		SetCallback = function(Callback: (Player: Player, Value: (string)) -> (({
			["success"]: (boolean),
			["message"]: (string),
		}))): () -> ()
			reliable_events[7] = Callback
			return function()
				reliable_events[7] = nil
			end
		end,
	},
}
type Events = typeof(returns)
return returns
